<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::create ([
            'title' => 'Porta celular para automóvil ajustable',
            'description' => 'Soporte universal para celular, se ajusta a cualquier tamaño. Ideal para usar GPS.',
            'condition' => 'new',
            'stock' => 50,
            'price' => 199.99,
            'warranty_type' => 'seller',
            'warranty_duration' => 6,
            'warranty_duration_type' => 'months',
            'status' => 'published',
            'user_id' => 3,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Cubre asientos de piel sintética',
            'description' => 'Juego completo de cubreasientos para automóvil, resistente al desgaste y fácil de limpiar.',
            'condition' => 'new',
            'stock' => 30,
            'price' => 899.99,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 1,
            'warranty_duration_type' => 'years',
            'status' => 'draft',
            'user_id' => 7,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Cargador USB para auto de doble entrada',
            'description' => 'Cargador rápido con dos puertos USB, compatible con todos los vehículos.',
            'condition' => 'new',
            'stock' => 100,
            'price' => 150.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 3,
            'warranty_duration_type' => 'months',
            'status' => 'published',
            'user_id' => 5,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Cámara de reversa con visión nocturna',
            'description' => 'Cámara HD con visión nocturna y amplio ángulo de visión. Fácil instalación.',
            'condition' => 'reaconditioned',
            'stock' => 20,
            'price' => 1200.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 1,
            'warranty_duration_type' => 'years',
            'status' => 'published',
            'user_id' => 8,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Set de herramientas para coche 20 piezas',
            'description' => 'Incluye desarmadores, llaves ajustables y pinzas en un estuche portátil.',
            'condition' => 'new',
            'stock' => 45,
            'price' => 499.99,
            'warranty_type' => 'seller',
            'warranty_duration' => 6,
            'warranty_duration_type' => 'months',
            'status' => 'draft',
            'user_id' => 4,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Alfombras para auto de goma antideslizante',
            'description' => 'Juego de alfombras universales para automóvil. Resistentes y fáciles de limpiar.',
            'condition' => 'new',
            'stock' => 80,
            'price' => 399.99,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 1,
            'warranty_duration_type' => 'years',
            'status' => 'published',
            'user_id' => 2,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Espejo retrovisor con pantalla LCD',
            'description' => 'Espejo retrovisor con pantalla integrada para cámara de reversa.',
            'condition' => 'reaconditioned',
            'stock' => 15,
            'price' => 1499.99,
            'warranty_type' => 'seller',
            'warranty_duration' => 1,
            'warranty_duration_type' => 'years',
            'status' => 'published',
            'user_id' => 6,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Polish para faros automotrices',
            'description' => 'Kit para pulir y restaurar faros opacos o amarillentos.',
            'condition' => 'new',
            'stock' => 60,
            'price' => 299.99,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 6,
            'warranty_duration_type' => 'months',
            'status' => 'draft',
            'user_id' => 9,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Tapa volante ergonómica',
            'description' => 'Cubierta para volante con diseño ergonómico y antideslizante.',
            'condition' => 'new',
            'stock' => 100,
            'price' => 250.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 3,
            'warranty_duration_type' => 'months',
            'status' => 'published',
            'user_id' => 5,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Compresor de aire portátil para coche',
            'description' => 'Compresor eléctrico ideal para inflar llantas y pelotas deportivas.',
            'condition' => 'new',
            'stock' => 25,
            'price' => 850.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 1,
            'warranty_duration_type' => 'years',
            'status' => 'published',
            'user_id' => 7,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Luz LED para interior de coche',
            'description' => 'Kit de luces LED multicolor controladas por Bluetooth.',
            'condition' => 'new',
            'stock' => 120,
            'price' => 300.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 3,
            'warranty_duration_type' => 'months',
            'status' => 'draft',
            'user_id' => 4,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Porta maletas para techo de coche',
            'description' => 'Porta maletas de aluminio con capacidad de hasta 50 kg.',
            'condition' => 'new',
            'stock' => 10,
            'price' => 4500.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 2,
            'warranty_duration_type' => 'years',
            'status' => 'published',
            'user_id' => 3,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Cubierta para coche impermeable',
            'description' => 'Protección contra lluvia, polvo y rayos UV. Tamaño universal.',
            'condition' => 'new',
            'stock' => 50,
            'price' => 800.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 6,
            'warranty_duration_type' => 'months',
            'status' => 'draft',
            'user_id' => 2,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Protector de llanta de refacción',
            'description' => 'Funda resistente para proteger la llanta de refacción de tu vehículo.',
            'condition' => 'new',
            'stock' => 70,
            'price' => 450.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 1,
            'warranty_duration_type' => 'years',
            'status' => 'published',
            'user_id' => 6,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Organizador de baúl plegable',
            'description' => 'Organizador para el baúl del coche con compartimentos ajustables.',
            'condition' => 'new',
            'stock' => 40,
            'price' => 600.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 3,
            'warranty_duration_type' => 'months',
            'status' => 'published',
            'user_id' => 8,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Kit de emergencia para coche',
            'description' => 'Incluye cables de corriente, triángulos de seguridad y botiquín básico.',
            'condition' => 'new',
            'stock' => 30,
            'price' => 950.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 1,
            'warranty_duration_type' => 'years',
            'status' => 'draft',
            'user_id' => 9,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Aromatizante para auto en barra',
            'description' => 'Aromatizante de larga duración con fragancia de vainilla.',
            'condition' => 'new',
            'stock' => 200,
            'price' => 50.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 1,
            'warranty_duration_type' => 'months',
            'status' => 'published',
            'user_id' => 1,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Portavasos para automóvil',
            'description' => 'Portavasos ajustable compatible con la mayoría de los vehículos.',
            'condition' => 'new',
            'stock' => 100,
            'price' => 120.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 6,
            'warranty_duration_type' => 'months',
            'status' => 'published',
            'user_id' => 2,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Protector de puertas anti golpes',
            'description' => 'Protector de goma adhesiva para evitar golpes y rasguños en las puertas.',
            'condition' => 'new',
            'stock' => 80,
            'price' => 300.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 3,
            'warranty_duration_type' => 'months',
            'status' => 'draft',
            'user_id' => 4,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Ganchos para reposacabezas de coche',
            'description' => 'Set de 4 ganchos para colgar bolsas y objetos en el asiento trasero.',
            'condition' => 'new',
            'stock' => 150,
            'price' => 120.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 1,
            'warranty_duration_type' => 'years',
            'status' => 'published',
            'user_id' => 3,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Espejo retrovisor extra largo',
            'description' => 'Espejo amplio para mayor visibilidad, fácil de instalar.',
            'condition' => 'new',
            'stock' => 60,
            'price' => 350.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 6,
            'warranty_duration_type' => 'months',
            'status' => 'draft',
            'user_id' => 7,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Cargador inalámbrico para auto',
            'description' => 'Cargador de carga rápida para smartphones con soporte ajustable.',
            'condition' => 'new',
            'stock' => 25,
            'price' => 1300.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 2,
            'warranty_duration_type' => 'years',
            'status' => 'published',
            'user_id' => 5,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Red de carga para baúl',
            'description' => 'Red elástica para sujetar objetos en el baúl del automóvil.',
            'condition' => 'new',
            'stock' => 90,
            'price' => 200.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 3,
            'warranty_duration_type' => 'months',
            'status' => 'published',
            'user_id' => 6,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Protector solar para parabrisas',
            'description' => 'Protector plegable para evitar el calor y rayos UV en el interior del coche.',
            'condition' => 'new',
            'stock' => 200,
            'price' => 180.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 1,
            'warranty_duration_type' => 'months',
            'status' => 'draft',
            'user_id' => 8,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Cámara DVR para grabación frontal',
            'description' => 'Cámara de alta resolución para grabar el recorrido del coche.',
            'condition' => 'reaconditioned',
            'stock' => 15,
            'price' => 2200.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 1,
            'warranty_duration_type' => 'years',
            'status' => 'published',
            'user_id' => 9,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Cubre volante de cuero sintético',
            'description' => 'Funda antideslizante con diseño elegante y cómodo.',
            'condition' => 'new',
            'stock' => 110,
            'price' => 320.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 6,
            'warranty_duration_type' => 'months',
            'status' => 'published',
            'user_id' => 2,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Cubre pedales deportivos',
            'description' => 'Set de cubre pedales antideslizantes con diseño deportivo para auto.',
            'condition' => 'new',
            'stock' => 80,
            'price' => 250.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 6,
            'warranty_duration_type' => 'months',
            'status' => 'draft',
            'user_id' => 3,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Tapete antideslizante para tablero',
            'description' => 'Tapete de silicona para colocar objetos pequeños en el tablero del coche.',
            'condition' => 'new',
            'stock' => 200,
            'price' => 120.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 1,
            'warranty_duration_type' => 'years',
            'status' => 'published',
            'user_id' => 5,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Refrigerador portátil para coche',
            'description' => 'Refrigerador compacto de 12V para mantener alimentos y bebidas frías.',
            'condition' => 'reaconditioned',
            'stock' => 10,
            'price' => 3200.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 2,
            'warranty_duration_type' => 'years',
            'status' => 'published',
            'user_id' => 7,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Cubierta de freno de mano',
            'description' => 'Funda para freno de mano en cuero sintético, elegante y cómoda.',
            'condition' => 'new',
            'stock' => 100,
            'price' => 180.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 6,
            'warranty_duration_type' => 'months',
            'status' => 'draft',
            'user_id' => 6,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Kit de limpieza para auto',
            'description' => 'Incluye esponjas, paños de microfibra y líquidos especiales para limpieza automotriz.',
            'condition' => 'new',
            'stock' => 150,
            'price' => 500.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 1,
            'warranty_duration_type' => 'years',
            'status' => 'published',
            'user_id' => 8,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Portabicicletas para coche',
            'description' => 'Soporte de alta resistencia para transportar hasta 3 bicicletas.',
            'condition' => 'new',
            'stock' => 20,
            'price' => 2800.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 2,
            'warranty_duration_type' => 'years',
            'status' => 'draft',
            'user_id' => 9,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Luz LED para matrícula',
            'description' => 'Luces LED de alta intensidad para iluminar la matrícula de tu coche.',
            'condition' => 'new',
            'stock' => 90,
            'price' => 200.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 3,
            'warranty_duration_type' => 'months',
            'status' => 'published',
            'user_id' => 1,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Forro para palanca de cambios',
            'description' => 'Funda de silicona para proteger la palanca de cambios.',
            'condition' => 'new',
            'stock' => 120,
            'price' => 150.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 1,
            'warranty_duration_type' => 'years',
            'status' => 'published',
            'user_id' => 2,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Cargador solar para batería de auto',
            'description' => 'Cargador portátil que utiliza energía solar para recargar la batería del coche.',
            'condition' => 'new',
            'stock' => 35,
            'price' => 1800.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 2,
            'warranty_duration_type' => 'years',
            'status' => 'draft',
            'user_id' => 3,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Adaptador Bluetooth para auto',
            'description' => 'Adaptador para transmitir música y llamadas a través de Bluetooth.',
            'condition' => 'new',
            'stock' => 60,
            'price' => 400.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 6,
            'warranty_duration_type' => 'months',
            'status' => 'published',
            'user_id' => 4,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Tira LED para luces exteriores',
            'description' => 'Tira de luces LED impermeable para personalizar la estética de tu coche.',
            'condition' => 'new',
            'stock' => 50,
            'price' => 300.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 1,
            'warranty_duration_type' => 'years',
            'status' => 'draft',
            'user_id' => 6,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Soporte para tablet en auto',
            'description' => 'Soporte ajustable para tablets, ideal para el entretenimiento de pasajeros.',
            'condition' => 'new',
            'stock' => 25,
            'price' => 600.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 2,
            'warranty_duration_type' => 'years',
            'status' => 'published',
            'user_id' => 7,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Funda para asientos impermeable',
            'description' => 'Protector de asientos impermeable, ideal para mascotas o derrames accidentales.',
            'condition' => 'new',
            'stock' => 75,
            'price' => 800.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 1,
            'warranty_duration_type' => 'years',
            'status' => 'published',
            'user_id' => 8,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Cubre motor térmico',
            'description' => 'Protector térmico para mantener la temperatura óptima del motor.',
            'condition' => 'new',
            'stock' => 30,
            'price' => 1500.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 2,
            'warranty_duration_type' => 'years',
            'status' => 'draft',
            'user_id' => 9,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Gato hidráulico portátil',
            'description' => 'Gato hidráulico compacto para elevar autos de hasta 2 toneladas.',
            'condition' => 'new',
            'stock' => 20,
            'price' => 2200.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 6,
            'warranty_duration_type' => 'months',
            'status' => 'published',
            'user_id' => 1,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Alarma para coche con control remoto',
            'description' => 'Sistema de seguridad con mando a distancia para mayor protección.',
            'condition' => 'new',
            'stock' => 15,
            'price' => 2500.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 1,
            'warranty_duration_type' => 'years',
            'status' => 'draft',
            'user_id' => 2,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Cortina para ventana lateral',
            'description' => 'Cortina ajustable para bloquear los rayos del sol en las ventanas del auto.',
            'condition' => 'new',
            'stock' => 100,
            'price' => 200.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 3,
            'warranty_duration_type' => 'months',
            'status' => 'published',
            'user_id' => 3,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Soporte magnético para celular',
            'description' => 'Soporte magnético para sujetar el teléfono en el tablero del coche.',
            'condition' => 'new',
            'stock' => 50,
            'price' => 350.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 1,
            'warranty_duration_type' => 'years',
            'status' => 'published',
            'user_id' => 4,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Cobertor impermeable para auto',
            'description' => 'Cobertor completo para proteger el auto de la lluvia y el polvo.',
            'condition' => 'new',
            'stock' => 45,
            'price' => 1800.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 1,
            'warranty_duration_type' => 'years',
            'status' => 'draft',
            'user_id' => 5,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Cojín lumbar para asientos de coche',
            'description' => 'Cojín ergonómico para mayor comodidad durante viajes largos.',
            'condition' => 'new',
            'stock' => 80,
            'price' => 400.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 6,
            'warranty_duration_type' => 'months',
            'status' => 'published',
            'user_id' => 6,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Cámara de reversa impermeable',
            'description' => 'Cámara resistente al agua con visión nocturna para estacionar con seguridad.',
            'condition' => 'new',
            'stock' => 30,
            'price' => 2500.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 2,
            'warranty_duration_type' => 'years',
            'status' => 'published',
            'user_id' => 7,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Protector de volante con masajeador',
            'description' => 'Funda de volante con puntos de masaje para mayor confort al conducir.',
            'condition' => 'new',
            'stock' => 120,
            'price' => 600.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 3,
            'warranty_duration_type' => 'months',
            'status' => 'draft',
            'user_id' => 8,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Luz LED ambiental para interiores',
            'description' => 'Kit de luces LED para personalizar el interior del coche.',
            'condition' => 'new',
            'stock' => 40,
            'price' => 900.00,
            'warranty_type' => 'manufacturer',
            'warranty_duration' => 1,
            'warranty_duration_type' => 'years',
            'status' => 'published',
            'user_id' => 9,
            'category_id' => 1,
        ]);
        Product::create ([
            'title' => 'Cubre llantas de repuesto',
            'description' => 'Funda resistente para proteger la llanta de repuesto de tu coche.',
            'condition' => 'new',
            'stock' => 60,
            'price' => 700.00,
            'warranty_type' => 'seller',
            'warranty_duration' => 6,
            'warranty_duration_type' => 'months',
            'status' => 'published',
            'user_id' => 1,
            'category_id' => 1,
        ]);
    }
}
