<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // ** AGREGAR SUS CATEGORÍAS Y PRODUCTOS **
        $categories = [
            25 => [ // Libros, Revistas y Comics
                'titles' => [
                    'El Juego De Ender',
                    'Cien Años De Soledad',
                    'Harry Potter y la Piedra Filosofal',
                    'El Señor De Los Anillos',
                    '1984',
                    'La Casa De Los Espíritus',
                    'El Alquimista',
                    'Orgullo y Prejuicio',
                    'Don Quijote De La Mancha',
                    'Los Pilares De La Tierra',
                    'Crónica De Una Muerte Anunciada',
                    'El Código Da Vinci',
                    'Los Miserables',
                    'Matar A Un Ruiseñor',
                    'La Sombra Del Viento',
                    'La Trilogía De La Fundación',
                    'Cumbres Borrascosas',
                    'Fahrenheit 451',
                    'El Retrato De Dorian Gray',
                    'Drácula',
                    'El Nombre Del Viento',
                    'El Hobbit',
                    'Rayuela',
                    'La Guerra De Los Mundos',
                    'La Metamorfosis',
                    'El Gran Gatsby',
                    'El Corazón Delator',
                    'El Psicoanalista',
                    'La Chica Del Tren',
                    'Comic El Regreso Del Caballero Oscuro, Edición Especial',
                ],
                'descriptions' => [
                    'Una obra maestra de la ciencia ficción sobre un niño prodigio que salva a la humanidad.',
                    'La historia épica de la familia Buendía, en el mágico Macondo, escrita por Gabriel García Márquez.',
                    'La primera entrega de la saga mágica que sigue a un joven mago en su lucha contra el mal.',
                    'La épica fantasía que narra la lucha contra el oscuro señor Sauron.',
                    'Una distopía que explora un futuro totalitario donde la vigilancia es omnipresente.',
                    'La historia de la vida de Clara, una joven que posee poderes psíquicos, y su familia.',
                    'La obra de Paulo Coelho sobre la búsqueda personal de un joven en la vida.',
                    'La historia de amor entre Elizabeth Bennet y el orgulloso Mr. Darcy.',
                    'Las aventuras de un caballero enloquecido por la lectura, en su lucha contra los molinos de viento.',
                    'Una de las novelas históricas más importantes, centrada en la construcción de una catedral.',
                    'Una novela de suspenso sobre el asesinato de un hombre en una ciudad costera.',
                    'Un thriller histórico que entrelaza arte, religión y misterio.',
                    'El clásico de Victor Hugo sobre la lucha de los oprimidos y la redención.',
                    'La historia conmovedora de una niña que crece en un pueblo del sur de los Estados Unidos.',
                    'Una novela que explora los secretos oscuros y misterios en la Barcelona de la posguerra.',
                    'Una serie de ciencia ficción que explora la caída y el ascenso de imperios galácticos.',
                    'El trágico romance de dos almas perdidas en los páramos de la Inglaterra victoriana.',
                    'Una crítica a la censura y la manipulación del conocimiento en una sociedad distópica.',
                    'Una obra maestra que explora la belleza del hedonismo y la corrupción en la sociedad victoriana.',
                    'La historia de la lucha entre el bien y el mal a través del vampiro más famoso.',
                    'El inicio de la famosa saga de fantasía que sigue al joven mago en su viaje.',
                    'Un estudio profundo de la complejidad de la literatura, la vida y la pasión.',
                    'La invasión alienígena que pone en peligro la supervivencia de la humanidad.',
                    'Una obra maestra de Kafka sobre la transformación y la alienación de un hombre.',
                    'La famosa novela que narra la vida decadente y las relaciones en la sociedad de Nueva York.',
                    'Un relato breve sobre la paranoia y el crimen en la mente humana.',
                    'El inquietante thriller psicológico que explora el misterio detrás de una desaparición.',
                    'Un thriller que explora la mente de un psicoanalista ante una amenaza mortal.',
                    'Un misterio psicológico que desafía la percepción de la verdad y la mentira.',
                    'Versión de lujo del clásico cómic, imprescindible para los fanáticos del género.',
                ],
            ],
            26 => [ // Música, Películas y Series
                'titles' => [
                    'Abbey Road',
                    'Thriller',
                    'The Dark Side of the Moon',
                    'Back in Black',
                    'Rumours',
                    'A Night at the Opera',
                    'The Wall',
                    'The Rise and Fall of Ziggy Stardust',
                    'Highway to Hell',
                    'Let It Be',
                    'The Velvet Underground & Nico',
                    'Sticky Fingers',
                    'The Joshua Tree',
                    'Born to Run',
                    'London Calling',
                    'Exile on Main St.',
                    'Goodfellas',
                    'Pulp Fiction',
                    'The Shawshank Redemption',
                    'Forrest Gump',
                    'Inception',
                    'The Godfather',
                    'The Dark Knight',
                    'Star Wars: A New Hope',
                    'The Matrix',
                    'Fight Club',
                    'Titanic',
                    'The Lord of the Rings: The Fellowship of the Ring',
                    'Breaking Bad',
                    'Stranger Things',
                ],
                'descriptions' => [
                    'El icónico álbum de The Beatles, conocido por sus canciones atemporales y su portada legendaria.',
                    'El álbum más vendido de todos los tiempos de Michael Jackson, con los éxitos “Billie Jean” y “Thriller”.',
                    'Un viaje psicodélico a través de la música de Pink Floyd, considerado uno de los mejores álbumes de todos los tiempos.',
                    'El legendario álbum de AC/DC, repleto de himnos de rock como “You Shook Me All Night Long”.',
                    'Uno de los álbumes más influyentes de Fleetwood Mac, con canciones como “Go Your Own Way”.',
                    'El álbum de Queen que presenta la famosa ópera rock “Bohemian Rhapsody”.',
                    'El majestuoso álbum de Pink Floyd que cuenta la historia de una alienación personal y social.',
                    'La obra maestra de David Bowie, donde presenta su personaje de Ziggy Stardust.',
                    'El emblemático álbum de AC/DC con el título que se convirtió en un himno del rock.',
                    'El último álbum de estudio de The Beatles, que contiene “Let It Be” y “Across the Universe”.',
                    'El álbum debut de The Velvet Underground, que cambió el curso de la música rock.',
                    'El aclamado álbum de The Rolling Stones con canciones como “Brown Sugar” y “Wild Horses”.',
                    'El exitoso álbum de U2, con “With or Without You” y “I Still Haven’t Found What I’m Looking For”.',
                    'El revolucionario álbum de Bruce Springsteen, que inspiró a generaciones con su himno “Born to Run”.',
                    'El álbum doble de The Clash que define el punk rock de los años 70 y 80.',
                    'El legendario álbum de The Rolling Stones grabado en el sur de Estados Unidos, lleno de alma y rock.',
                    'La película épica sobre la mafia que fue dirigida por Martin Scorsese y protagonizada por Robert De Niro.',
                    'La película de Quentin Tarantino que cambió el cine contemporáneo con sus diálogos icónicos y narrativa no lineal.',
                    'La conmovedora historia sobre la amistad en prisión y la búsqueda de la redención.',
                    'La entrañable película que mezcla comedia y drama mientras narra la vida de Forrest Gump.',
                    'El thriller de Christopher Nolan que desafía la percepción del tiempo y la realidad.',
                    'La obra maestra de Francis Ford Coppola sobre la mafia y el poder familiar.',
                    'La aclamada película de Christopher Nolan que sigue las aventuras del Caballero Oscuro en Gotham.',
                    'El primer capítulo de la famosa saga galáctica que cambió la historia del cine.',
                    'La película de ciencia ficción que revolucionó el cine con su exploración de la realidad y la simulación.',
                    'La película de David Fincher que explora los límites de la psique humana y el consumismo.',
                    'La conmovedora historia de amor que marcó a toda una generación, protagonizada por Leonardo DiCaprio y Kate Winslet.',
                    'La épica adaptación cinematográfica de la obra de Tolkien, que inicia la trilogía de “El Señor de los Anillos”.',
                    'La aclamada serie que sigue a un profesor de química convertido en fabricante de metanfetaminas.',
                    'La serie de terror y ciencia ficción que se ha convertido en un fenómeno cultural.',
                ],
            ],
            27 => [ // Recuerdos, Cotillón y Fiestas 
                'titles' => [
                    'Sombrero Fiesta Animado',
                    'Globos Metalizados 10 Piezas',
                    'Piñata Cumpleaños Infantil',
                    'Kit Fiesta Temática Marvel',
                    'Lentejuelas Brillantes para Fiesta',
                    'Cinta Decorativa de Regalo',
                    'Vela Cumpleaños con Número',
                    'Letras Gigantes para Fiesta',
                    'Conos de Confeti para Boda',
                    'Disfraces Infantiles De Halloween',
                    'Bolsas para Regalos con Diseño',
                    'Tazas Personalizadas para Fiestas',
                    'Decoración para Fiesta de Año Nuevo',
                    'Guirnaldas de Papel para Fiesta',
                    'Mantel de Plástico para Fiesta Infantil',
                    'Máscara de Carnaval para Adultos',
                    'Pulseras de Fiesta de Colores',
                    'Banderines de Fiesta',
                    'Estrellas Colgantes para Decoración',
                    'Sombrero de Conejo para Fiesta',
                    'Lámparas LED para Fiestas',
                    'Caramelos Temáticos para Fiestas',
                    'Toppers de Pastel para Cumpleaños',
                    'Collares de Flores para Fiesta',
                    'Tarjetas de Invitación Personalizadas',
                    'Túmulo de Globo para Fiestas',
                    'Bolsa de Sorpresas para Fiesta Infantil',
                    'Cadenas de Papel para Fiesta de Navidad',
                    'Pañuelos para Fiestas Temáticas',
                    'Juguetes de Fiesta para Niños',
                ],
                'descriptions' => [
                    'Sombrero colorido y animado perfecto para cualquier fiesta temática.',
                    'Pack de globos metalizados en diversos colores, ideales para decorar cualquier celebración.',
                    'Piñata de temática infantil para fiesta de cumpleaños, fácil de llenar y romper.',
                    'Kit completo de fiesta con productos de temática Marvel para los fans de los superhéroes.',
                    'Lentejuelas brillantes para añadir un toque de glamour a tu fiesta de noche.',
                    'Cinta decorativa para envolver regalos o para usar en decoración de eventos especiales.',
                    'Vela para pastel con el número de tu preferencia para celebrar tu cumpleaños.',
                    'Letras gigantes de cartón para decorar y personalizar tu fiesta o evento.',
                    'Conos de confeti para bodas, perfectos para lanzar al final de la ceremonia.',
                    'Disfraz infantil para Halloween, con diferentes personajes disponibles para escoger.',
                    'Bolsas de regalo de alta calidad con diseños modernos y divertidos.',
                    'Tazas personalizadas para obsequiar como recuerdo en eventos especiales.',
                    'Decoración festiva para Año Nuevo, incluye guirnaldas y banderines brillantes.',
                    'Guirnalda de papel de colores vivos para decorar salas de fiestas o jardines.',
                    'Mantel de plástico desechable para fiestas infantiles, con temática de superhéroes.',
                    'Máscara de carnaval para adultos, disponible en diferentes estilos y colores.',
                    'Pulseras de fiesta en diversos colores y formas, perfectas para eventos y festivales.',
                    'Banderines con letras personalizadas, ideales para fiestas de cumpleaños o bodas.',
                    'Estrellas decorativas de papel para colgar en el techo y crear un ambiente festivo.',
                    'Sombrero de conejo de peluche para fiestas de primavera o eventos temáticos.',
                    'Lámpara LED de colores, perfecta para iluminar fiestas al aire libre o en interiores.',
                    'Caramelos temáticos para fiestas, personalizables con los colores del evento.',
                    'Toppers decorativos para pasteles de cumpleaños, con diferentes temáticas disponibles.',
                    'Collares de flores para decorar a los invitados durante una fiesta tropical o hawaiana.',
                    'Tarjetas de invitación personalizadas con tema de boda o cumpleaños para invitados.',
                    'Túmulo de globos para decoración de fiestas infantiles, fácil de montar y colorido.',
                    'Bolsa de sorpresas con pequeños obsequios para niños en fiestas temáticas.',
                    'Cadenas de papel decorativas para fiestas de Navidad, con diseño clásico y colorido.',
                    'Pañuelos de colores para fiesta de baile, disponibles en varias tonalidades.',
                    'Juguetes pequeños para niños, perfectos como recuerdos para fiestas infantiles.',
                ],
            ],
            28 => [ // Ropa, Bolsas y Calzado
                'titles' => [
                    'Zapatos de Cuero Para Hombre',
                    'Bolso de Mano de Piel',
                    'Chaqueta de Cuero para Mujer',
                    'Pantalones Deportivos Unisex',
                    'Camiseta de Algodón con Estampado',
                    'Gorra de Béisbol con Logo',
                    'Botines de Mujer en Ante',
                    'Sandalias de Playa para Hombre',
                    'Chaleco de Lana para Invierno',
                    'Pantalón de Trabajo para Hombre',
                    'Mochila de Tela Resistente',
                    'Zapatillas Deportivas para Mujer',
                    'Vestido Corto de Verano',
                    'Pantalones Vaqueros de Corte Slim',
                    'Bolso de Mano con Correa Ajustable',
                    'Botas de Invierno de Mujer',
                    'Cinturón de Cuero para Hombre',
                    'Sudadera con Capucha para Niño',
                    'Botas de Lluvia para Mujer',
                    'Pantalones Cortos de Tela Ligera',
                    'Camiseta Sin Mangas para Hombre',
                    'Zapatillas de Running para Hombre',
                    'Bolso de Viaje de Mano',
                    'Gorro de Invierno con Forro Polar',
                    'Chaqueta de Invierno con Capucha',
                    'Blusa de Seda para Mujer',
                    'Billetera de Cuero para Hombre',
                    'Sandalias de Cuero para Mujer',
                    'Zapatos de Noche para Mujer',
                    'Bolso Tote De Cuero Vegano, Diseño Minimalista',
                ],
                'descriptions' => [
                    'Zapatos de cuero de alta calidad, ideales para ocasiones formales o casuales.',
                    'Bolso de mano de piel genuina, perfecto para el día a día o eventos especiales.',
                    'Chaqueta de cuero para mujer, con diseño elegante y moderno, perfecta para las noches frescas.',
                    'Pantalones deportivos cómodos y versátiles para hombres y mujeres de todas las edades.',
                    'Camiseta de algodón con estampado divertido y colores vibrantes, cómoda y fresca.',
                    'Gorra de béisbol con logo bordado, ideal para deportes o como accesorio casual.',
                    'Botines de mujer en ante suave, adecuados para el clima frío o como complemento de estilo.',
                    'Sandalias cómodas y ligeras, perfectas para días de verano y playa.',
                    'Chaleco de lana para invierno, ligero pero cálido, ideal para layering.',
                    'Pantalón de trabajo resistente para hombres, con bolsillos y estilo práctico.',
                    'Mochila resistente y ligera, ideal para viajes o uso escolar diario.',
                    'Zapatillas deportivas de mujer, diseñadas para confort y rendimiento en actividades físicas.',
                    'Vestido corto de verano, fresco y elegante para ocasiones informales o vacaciones.',
                    'Pantalones vaqueros de corte slim para hombre, modernos y cómodos para el uso diario.',
                    'Bolso de mano con correa ajustable, práctico y espacioso, adecuado para diversas ocasiones.',
                    'Botas de invierno de mujer, forradas para mantener los pies calientes en el clima frío.',
                    'Cinturón de cuero para hombre, elegante y resistente, para todo tipo de ocasiones.',
                    'Sudadera con capucha para niño, suave y cómoda, perfecta para días fríos o relajados.',
                    'Botas de lluvia para mujer, impermeables y cómodas, ideales para días lluviosos.',
                    'Pantalones cortos de tela ligera, cómodos para los días calurosos de verano.',
                    'Camiseta sin mangas para hombre, fresca y cómoda para los días cálidos.',
                    'Zapatillas de running para hombre, diseñadas para máximo confort en carreras largas.',
                    'Bolso de viaje de mano, espacioso y con compartimentos para organizar pertenencias.',
                    'Gorro de invierno con forro polar, ideal para mantener el calor en los días fríos.',
                    'Chaqueta de invierno con capucha, resistente al viento y al frío, esencial para el invierno.',
                    'Blusa de seda para mujer, elegante y suave, ideal para ocasiones formales o de noche.',
                    'Billetera de cuero para hombre, compacta y elegante, con varios compartimentos.',
                    'Sandalias de cuero para mujer, cómodas y de estilo clásico, perfectas para el verano.',
                    'Zapatos de noche de mujer, elegantes y sofisticados para eventos especiales.',
                    'Bolso moderno y funcional, perfecto para el uso diario, hecho con materiales ecológicos.',
                ],
            ],
        ];

        foreach ($categories as $categoryId => $data) {
            $totalProducts = count($data['titles']); // Total de títulos disponibles en esta categoría
            for ($i = 0; $i < $totalProducts; $i++) { // 30 productos por categoría
                Product::create([
                    'title' => $data['titles'][$i],
                    'description' => $data['descriptions'][$i],
                    'condition' => ['new', 'used', 'reaconditioned'][array_rand(['new', 'used', 'reaconditioned'])],
                    'stock' => rand(10, 200),
                    'price' => rand(100, 5000),
                    'publication_type' => ['free', 'classic', 'premium'][array_rand(['free', 'classic', 'premium'])],
                    'warranty_type' => ['manufacturer', 'seller'][array_rand(['manufacturer', 'seller'])],
                    'warranty_duration' => rand(1, 24),
                    'warranty_duration_type' => ['days', 'months', 'years'][array_rand(['days', 'months', 'years'])],
                    'status' => ['draft', 'published'][array_rand(['draft', 'published'])],
                    'user_id' => rand(1, 9),
                    'category_id' => $categoryId,
                ]);
            }
        }
    }
}
