<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // ** AGREGAR SUS CATEGORÍAS Y PRODUCTOS **
        $categories = [
            1 => [ // Accesorios para vehículos
                'titles' => [
                    'Cubre asientos de lujo',
                    'Tapetes impermeables',
                    'Espejo retrovisor inteligente',
                    'Soporte para celular',
                    'Cargador rápido USB para auto',
                    'Parasol para parabrisas',
                    'Portaequipajes de techo',
                    'Funda para volante',
                    'Luces LED para auto',
                    'Organizador de asiento trasero',
                    'Detector de puntos ciegos',
                    'Cámara de reversa',
                    'Cera pulidora para carrocería',
                    'Kit de emergencia vial',
                    'Aspiradora portátil para auto',
                    'Ambientador de aire',
                    'Reproductor multimedia para auto',
                    'Película protectora de pintura',
                    'Escobillas limpiaparabrisas',
                    'Kit de herramientas básico',
                    'Cargador solar para auto',
                    'Soporte para bicicletas',
                    'Convertidor de corriente para auto',
                    'Kit de limpieza para auto',
                    'Protector de asiento infantil',
                    'Lámpara de trabajo LED',
                    'Alarma antirrobo',
                    'Compresor portátil para neumáticos',
                    'Reflectores de emergencia',
                    'Sensor de estacionamiento',
                ],
                'descriptions' => [
                    'Cubre asientos resistente al desgaste.',
                    'Tapetes ideales para cualquier clima.',
                    'Espejo con pantalla para navegación.',
                    'Soporte ajustable para todos los teléfonos.',
                    'Cargador dual con tecnología rápida.',
                    'Protección solar para el interior del auto.',
                    'Espacio extra para viajes largos.',
                    'Funda con diseño ergonómico.',
                    'Luces LED de alta intensidad.',
                    'Organizador con múltiples compartimentos.',
                    'Mayor seguridad al cambiar de carril.',
                    'Cámara HD para una mejor visibilidad.',
                    'Brillo y protección para tu carrocería.',
                    'Incluye herramientas esenciales para emergencias.',
                    'Limpieza rápida y eficiente en el auto.',
                    'Fragancia duradera para tu vehículo.',
                    'Reproducción multimedia moderna.',
                    'Protege la pintura de rayones.',
                    'Escobillas resistentes al clima.',
                    'Herramientas prácticas y portátiles.',
                    'Cargador ecológico y eficiente.',
                    'Transporta bicicletas de forma segura.',
                    'Convierte corriente para dispositivos.',
                    'Mantén limpio el interior de tu auto.',
                    'Seguridad para los más pequeños.',
                    'Iluminación fuerte para reparaciones.',
                    'Protección adicional contra robos.',
                    'Infla neumáticos rápidamente.',
                    'Mayor visibilidad en emergencias.',
                    'Ayuda a estacionar con precisión.',
                ],
            ],
            2 => [ // Agro
                'titles' => [
                    'Fertilizante orgánico premium',
                    'Insecticida natural concentrado',
                    'Semillas de hortalizas mixtas',
                    'Rastrillo de acero inoxidable',
                    'Sistema de riego por goteo',
                    'Pala para jardinería',
                    'Abono enriquecido con nutrientes',
                    'Guantes resistentes para jardinería',
                    'Corta césped manual',
                    'Aspersor de agua ajustable',
                    'Kit de herramientas de jardinería',
                    'Malla para proteger cultivos',
                    'Macetas biodegradables',
                    'Sustrato especial para plantas',
                    'Controlador de plagas ultrasónico',
                    'Termómetro para suelo',
                    'Compostador portátil',
                    'Semillas de césped resistente',
                    'Tijeras de poda ergonómicas',
                    'Pala multiusos para campo',
                    'Carretilla plegable',
                    'Kit de mantenimiento para huerto',
                    'Riego automático programable',
                    'Tractor de juguete educativo',
                    'Aceite natural para plantas',
                    'Caja de herramientas para campo',
                    'Mini invernadero portátil',
                    'Sistema de captación de agua',
                    'Corta setos eléctrico',
                    'Sensor de humedad para cultivos',
                ],
                'descriptions' => [
                    'Fertilizante ideal para cultivos ecológicos.',
                    'Insecticida seguro para plantas y animales.',
                    'Mezcla de semillas de fácil cultivo.',
                    'Rastrillo durable y eficiente.',
                    'Ahorra agua con un riego eficiente.',
                    'Pala ligera y resistente.',
                    'Abono orgánico con alto rendimiento.',
                    'Guantes cómodos y duraderos.',
                    'Perfecto para jardines pequeños.',
                    'Aspersor ajustable para todos los tipos de cultivos.',
                    'Incluye todo lo necesario para el jardín.',
                    'Protección eficaz contra aves e insectos.',
                    'Macetas ecológicas y reutilizables.',
                    'Sustrato de calidad para mejores resultados.',
                    'Ahorra tiempo en el control de plagas.',
                    'Mide la temperatura del suelo fácilmente.',
                    'Ideal para reciclar desechos orgánicos.',
                    'Césped verde y resistente en cualquier clima.',
                    'Tijeras cómodas y precisas.',
                    'Versátil para todo tipo de terrenos.',
                    'Fácil transporte de herramientas.',
                    'Todo lo que necesitas para tu huerto.',
                    'Riego automatizado para mayor comodidad.',
                    'Juguete educativo para niños.',
                    'Protege tus plantas con aceite natural.',
                    'Almacenamiento práctico para herramientas.',
                    'Crea un microclima ideal para tus plantas.',
                    'Aprovecha el agua de lluvia.',
                    'Corte preciso para setos perfectos.',
                    'Monitorea el estado de tus cultivos.',
                ],
            ],
            3 => [ // Alimentos y bebidas
                'titles' => [
                    'Chocolate artesanal', 
                    'Café orgánico molido', 
                    'Mermelada de fresa natural', 
                    'Aceite de oliva extra virgen', 
                    'Miel de abeja pura', 
                    'Té verde importado', 
                    'Cereal integral con frutos secos', 
                    'Salsa picante gourmet', 
                    'Queso parmesano rallado', 
                    'Galletas veganas de avena', 
                    'Arroz basmati premium', 
                    'Vino tinto reserva especial', 
                    'Cerveza artesanal IPA', 
                    'Agua mineral con gas', 
                    'Jugo natural de naranja', 
                    'Pasta de trigo integral', 
                    'Harina de almendra', 
                    'Chocolate en polvo sin azúcar', 
                    'Azúcar de coco orgánica', 
                    'Chips de plátano deshidratado', 
                    'Frutas deshidratadas mixtas', 
                    'Nueces caramelizadas', 
                    'Barritas energéticas de proteína', 
                    'Cacahuates tostados con miel', 
                    'Pan artesanal de masa madre', 
                    'Leche de almendra sin azúcar', 
                    'Helado vegano de coco', 
                    'Sopa instantánea gourmet', 
                    'Caviar negro', 
                    'Puré de manzana natural',
                ],
                'descriptions' => [
                    'Chocolate hecho a mano con cacao puro.', 
                    'Café de calidad premium para amantes del buen café.', 
                    'Mermelada elaborada con fresas frescas.', 
                    'Aceite de oliva de primera prensada en frío.', 
                    'Miel recolectada de colmenas naturales.', 
                    'Té verde con un aroma y sabor únicos.', 
                    'Cereal nutritivo y perfecto para el desayuno.', 
                    'Salsa picante elaborada con ingredientes naturales.', 
                    'Queso de alta calidad listo para usar.', 
                    'Galletas veganas deliciosas y saludables.', 
                    'Arroz ideal para recetas gourmet.', 
                    'Vino con un sabor intenso y bien balanceado.', 
                    'Cerveza artesanal con toques cítricos.', 
                    'Agua mineral de manantial natural.', 
                    'Jugo 100% natural sin conservantes.', 
                    'Pasta rica en fibra y nutrientes.', 
                    'Harina perfecta para recetas saludables.', 
                    'Chocolate en polvo ideal para repostería.', 
                    'Azúcar alternativa para endulzar naturalmente.', 
                    'Snacks saludables y crujientes.', 
                    'Frutas deshidratadas ideales para colaciones.', 
                    'Nueces dulces y crujientes.', 
                    'Barritas ideales para energía extra.', 
                    'Cacahuates dulces con un toque especial.', 
                    'Pan horneado artesanalmente.', 
                    'Leche vegetal ideal para intolerantes a la lactosa.', 
                    'Helado con textura cremosa y sabor tropical.', 
                    'Sopa lista en minutos con un toque gourmet.', 
                    'Caviar de la más alta calidad.', 
                    'Puré sin azúcar añadido para disfrutar.',
                ],
            ],
            4 => [ // Animales y mascotas
                'titles' => [
                    'Collar reflectante para perros', 
                    'Comida premium para gatos', 
                    'Juguete interactivo para mascotas', 
                    'Rascador para gatos con diseño moderno', 
                    'Cama acolchonada para perros grandes', 
                    'Cepillo para eliminar pelo muerto', 
                    'Transportadora portátil para mascotas', 
                    'Dispensador automático de agua', 
                    'Jaula para aves pequeñas', 
                    'Arena para gatos de alta absorción', 
                    'Suéter para perros pequeños', 
                    'Peluche resistente para morder', 
                    'Correa extensible de 5 metros', 
                    'Piedras decorativas para acuarios', 
                    'Foco LED para terrarios', 
                    'Espejo con campana para aves', 
                    'Alimento balanceado para peces', 
                    'Caseta de madera para exteriores', 
                    'Kit de aseo para mascotas', 
                    'Ropa impermeable para días de lluvia', 
                    'Arnés ajustable para gatos', 
                    'Snacks saludables para perros', 
                    'Cueva para roedores', 
                    'Accesorios para jaulas de hámster', 
                    'Lámpara UV para reptiles', 
                    'Filtro para acuarios pequeños', 
                    'Hueso masticable sabor pollo', 
                    'Alfombra absorbente para entrenamiento', 
                    'Juguete dispensador de comida', 
                    'Cuenco plegable para viajes',
                ],
                'descriptions' => [
                    'Collar con material reflectante para mayor seguridad.', 
                    'Comida rica en nutrientes y sabor.', 
                    'Juguete diseñado para estimular a tu mascota.', 
                    'Rascador con materiales duraderos.', 
                    'Cama cómoda para perros de gran tamaño.', 
                    'Cepillo que reduce el pelo en casa.', 
                    'Transportadora ligera y fácil de usar.', 
                    'Agua fresca siempre disponible.', 
                    'Jaula espaciosa para aves pequeñas.', 
                    'Arena que elimina olores y es fácil de limpiar.', 
                    'Suéter para mantener a tu perro abrigado.', 
                    'Peluche resistente para horas de diversión.', 
                    'Correa perfecta para paseos largos.', 
                    'Piedras ideales para decorar acuarios.', 
                    'Luz LED para mejorar el ambiente del terrario.', 
                    'Espejo divertido para entretener a tus aves.', 
                    'Alimento que mantiene a tus peces saludables.', 
                    'Caseta duradera y resistente a la intemperie.', 
                    'Incluye cepillos y cortaúñas.', 
                    'Mantén a tu mascota seca bajo la lluvia.', 
                    'Arnés seguro y cómodo.', 
                    'Premios ideales para entrenamiento.', 
                    'Cueva acogedora para pequeños roedores.', 
                    'Accesorios que hacen más divertido el hábitat.', 
                    'Luz UV esencial para reptiles.', 
                    'Filtro que mejora la calidad del agua.', 
                    'Hueso masticable para mantener dientes limpios.', 
                    'Alfombra ideal para entrenar a tu cachorro.', 
                    'Juguete que combina diversión y alimentación.', 
                    'Cuenco portátil y fácil de guardar.',
                ],
            ],
            5 => [ // Antigüedades y colecciones
                'titles' => [
                    'Reloj antiguo de bolsillo',
                    'Mapa histórico de 1800',
                    'Set de monedas coleccionables',
                    'Figura de porcelana clásica',
                    'Libro antiguo de recetas',
                    'Cuadro de arte renacentista',
                    'Sello postal de edición limitada',
                    'Espada medieval auténtica',
                    'Baúl vintage restaurado',
                    'Candelabro de bronce antiguo',
                    'Vajilla victoriana completa',
                    'Espejo barroco ornamentado',
                    'Fotografía histórica original',
                    'Juguete de madera artesanal',
                    'Lámpara de petróleo antigua',
                    'Máquina de escribir clásica',
                    'Teléfono de disco retro',
                    'Bastón de madera tallado',
                    'Set de llaves antiguas',
                    'Estatuilla de mármol clásico',
                    'Pintura al óleo de 1900',
                    'Caja de música antigua',
                    'Camafeo con marco de oro',
                    'Pergamino escrito a mano',
                    'Instrumento musical de época',
                    'Tetera de plata inglesa',
                    'Gafas de lectura vintage',
                    'Pluma estilográfica de colección',
                    'Reloj de pared clásico',
                    'Álbum fotográfico del siglo XIX',
                ],
                'descriptions' => [
                    'Pieza única en excelente estado.',
                    'Ideal para coleccionistas exigentes.',
                    'Rara antigüedad con gran valor histórico.',
                    'Diseño clásico y detalles únicos.',
                    'Perfecto para decorar espacios vintage.',
                    'Autenticidad garantizada por expertos.',
                    'Incluye certificado de autenticidad.',
                    'Restaurado manteniendo su esencia original.',
                    'Representa una época histórica importante.',
                    'Gran detalle en su diseño artesanal.',
                    'Perfecto para amantes de las antigüedades.',
                    'Conserva su estructura original.',
                    'Edición limitada difícil de encontrar.',
                    'Elegante y funcional, ideal para colección.',
                    'Proveniente de una exclusiva colección privada.',
                    'Históricamente significativo para el período.',
                    'Increíble estado de conservación.',
                    'Rico en historia y tradición.',
                    'Original y único en su tipo.',
                    'Perfecto para exposiciones o museos.',
                    'Gran adición a cualquier colección seria.',
                    'Diseño atemporal que nunca pasa de moda.',
                    'Proveniente de la región europea.',
                    'Un auténtico testimonio del pasado.',
                    'Fiel representación de un estilo clásico.',
                    'Alta calidad en los materiales empleados.',
                    'Pieza rara con gran valor sentimental.',
                    'Impecable restauración y presentación.',
                    'Atractivo diseño que cautiva a todos.',
                    'Ideal para decorar espacios sofisticados.',
                ],
            ],
            6 => [ // Arte, Papelería y Mercería
                'titles' => [
                    'Set de pinceles profesionales',
                    'Cuaderno de bocetos premium',
                    'Kit de pintura al óleo completo',
                    'Lápices de colores de alta gama',
                    'Caballete de madera ajustable',
                    'Bloc de acuarela de alta calidad',
                    'Tinta china para caligrafía',
                    'Set de bordado tradicional',
                    'Kit de herramientas para scrapbooking',
                    'Rollos de papel adhesivo decorativo',
                    'Set de bolígrafos de gel metálicos',
                    'Marcadores permanentes resistentes',
                    'Pegamento multiusos profesional',
                    'Set de tijeras de precisión',
                    'Perforadora decorativa para manualidades',
                    'Kit de costura portátil',
                    'Cinta de doble cara resistente',
                    'Regla de acero inoxidable',
                    'Cutter de precisión ergonómico',
                    'Portaminas de diseño elegante',
                    'Caja organizadora para materiales',
                    'Set de sellos personalizados',
                    'Témperas no tóxicas para niños',
                    'Hilos de bordar multicolor',
                    'Cartulina de colores brillantes',
                    'Rotuladores para lettering',
                    'Marcadores de punta fina',
                    'Set de plastilina modelable',
                    'Estuche rígido para materiales de arte',
                    'Kit de pintura en miniatura',
                ],
                'descriptions' => [
                    'Perfecto para artistas y principiantes.',
                    'Alta calidad garantizada para resultados profesionales.',
                    'Ideal para explorar tu creatividad.',
                    'Diseñado para durar y ofrecer precisión.',
                    'Materiales de alta calidad.',
                    'Incluye todo lo necesario para proyectos creativos.',
                    'Ligero y fácil de transportar.',
                    'Gran variedad de colores disponibles.',
                    'Diseño compacto y funcional.',
                    'Producto no tóxico y amigable con el medio ambiente.',
                    'Diseñado pensando en la comodidad del usuario.',
                    'Papel de excelente gramaje.',
                    'Versátil y compatible con diversos materiales.',
                    'Detalles precisos en cada trazo.',
                    'Perfecto para proyectos escolares.',
                    'Duradero y resistente al uso diario.',
                    'Colores vibrantes y llamativos.',
                    'Perfecto para trabajos detallados.',
                    'Diseño ergonómico para mayor comodidad.',
                    'Incluye instrucciones detalladas.',
                    'Materiales resistentes y seguros.',
                    'Apto para todas las edades.',
                    'Gran calidad a un precio competitivo.',
                    'Incluye accesorios adicionales para más opciones.',
                    'Perfecto para manualidades creativas.',
                    'Fácil de usar y almacenar.',
                    'Diseño innovador y práctico.',
                    'Proporciona un acabado profesional.',
                    'Adecuado para uso en interiores y exteriores.',
                    'Calidad superior con resultados garantizados.',
                ],
            ],
            7 => [ // Autos, Motos y Otros 
                'titles' => [
                    'Auto deportivo de lujo',
                    'Motocicleta todo terreno',
                    'Camioneta familiar espaciosa',
                    'Bicicleta eléctrica moderna',
                    'Remolque para carga',
                    'Scooter eléctrico compacto',
                    'Coche clásico restaurado',
                    'Vehículo híbrido económico',
                    'Auto compacto de ciudad',
                    'Caravana de camping equipada',
                    'Llantas todo terreno',
                    'Reproductor multimedia para auto',
                    'Sistema de navegación GPS',
                    'Alarma de seguridad para autos',
                    'Portabicicletas ajustable',
                    'Faros LED para autos',
                    'Kit de herramientas automotrices',
                    'Cargador portátil para baterías',
                    'Parabrisas reforzado',
                    'Casco de motocicleta profesional',
                    'Guantes de conducción táctiles',
                    'Maletero adicional para autos',
                    'Asientos de cuero personalizados',
                    'Cámara de reversa inalámbrica',
                    'Cadenas para nieve de alta resistencia',
                    'Motor de motocicleta de alto rendimiento',
                    'Luces de neón para autos',
                    'Defensa frontal de acero',
                    'Kit de suspensión deportiva',
                    'Sistema de sonido premium para autos',
                ],
                'descriptions' => [
                    'Diseño moderno y elegante.',
                    'Perfecto para viajes largos.',
                    'Incluye garantía extendida.',
                    'Ideal para entusiastas de la velocidad.',
                    'Resistente a todo tipo de clima.',
                    'Fácil de usar y mantener.',
                    'Calidad certificada por expertos.',
                    'Gran desempeño y eficiencia.',
                    'Equipado con tecnología avanzada.',
                    'Perfecto para familias numerosas.',
                    'Construido para durar muchos años.',
                    'Diseño ergonómico y funcional.',
                    'Compatibilidad universal.',
                    'Protección garantizada en todo momento.',
                    'Fabricado con materiales de alta calidad.',
                    'Fácil instalación sin herramientas adicionales.',
                    'Ligero y altamente duradero.',
                    'Rendimiento excepcional en carretera.',
                    'Asegura máxima visibilidad nocturna.',
                    'Práctico y seguro para cualquier conductor.',
                    'Mejora el rendimiento del vehículo.',
                    'Diseño compacto para fácil almacenamiento.',
                    'Proporciona una experiencia de conducción superior.',
                    'Estilo único para personalizar tu vehículo.',
                    'Ideal para actividades de aventura.',
                    'Aumenta la seguridad en condiciones extremas.',
                    'Potencia inigualable en su categoría.',
                    'Diseño innovador y práctico.',
                    'Calidad superior en cada detalle.',
                    'Compatible con múltiples modelos de vehículos.',
                ],
            ],
            8 => [ // Bebés
                'titles' => [
                    'Cuna convertible de madera',
                    'Cochecito de bebé plegable',
                    'Silla de auto para recién nacidos',
                    'Monitor de video para bebés',
                    'Set de biberones anticolic',
                    'Juguete educativo interactivo',
                    'Pañales ecológicos reutilizables',
                    'Cuna de viaje portátil',
                    'Mecedora con vibración relajante',
                    'Termómetro digital para bebés',
                    'Almohada para lactancia',
                    'Cojín antivuelco para recién nacidos',
                    'Set de ropa de algodón orgánico',
                    'Cucharas de silicona para bebés',
                    'Baberos impermeables ajustables',
                    'Esterilizador de biberones eléctrico',
                    'Columpio automático para bebés',
                    'Set de mordedores refrigerantes',
                    'Cuna de colecho ajustable',
                    'Caja organizadora de pañales',
                    'Humidificador ultrasónico para bebés',
                    'Piscina inflable para bebés',
                    'Alfombra de juegos acolchada',
                    'Andador con actividades interactivas',
                    'Toallas suaves de algodón',
                    'Bolsa de pañales multifuncional',
                    'Set de baño para bebés',
                    'Termos para líquidos infantiles',
                    'Protector de esquina para muebles',
                    'Cámara de vigilancia inalámbrica',
                ],
                'descriptions' => [
                    'Diseño seguro y confortable.',
                    'Fácil de transportar y almacenar.',
                    'Fabricado con materiales no tóxicos.',
                    'Ideal para monitorear a tu bebé.',
                    'Garantiza comodidad en cada uso.',
                    'Desarrolla habilidades motoras.',
                    'Diseño sostenible y ecológico.',
                    'Ligera y fácil de montar.',
                    'Asegura el descanso del bebé.',
                    'Lectura precisa y rápida.',
                    'Proporciona soporte durante la lactancia.',
                    'Previene caídas accidentales.',
                    'Textura suave y delicada.',
                    'Apto para alimentos calientes y fríos.',
                    'Fácil de limpiar y reutilizar.',
                    'Elimina bacterias de forma eficaz.',
                    'Ayuda a calmar al bebé rápidamente.',
                    'Perfecto para aliviar molestias dentales.',
                    'Se adapta a cualquier cama.',
                    'Mantén todo organizado y a la mano.',
                    'Ayuda a mejorar la calidad del sueño.',
                    'Perfecta para días calurosos.',
                    'Proporciona un espacio seguro de juego.',
                    'Fomenta el aprendizaje y la exploración.',
                    'Absorbe perfectamente el agua.',
                    'Diseñada para padres ocupados.',
                    'Incluye todo lo esencial para el baño.',
                    'Mantiene líquidos a la temperatura ideal.',
                    'Protege a los bebés de lesiones.',
                    'Fácil de instalar y operar.',
                ],
            ],
            9 => [ // Belleza y Cuidado Personal
                'titles' => [
                   'Crema hidratante facial',
                   'Set de brochas de maquillaje',
                   'Perfume floral de larga duración',
                   'Champú anticaída',
                   'Gel limpiador facial',
                   'Mascarilla capilar regeneradora',
                   'Base de maquillaje mate',
                   'Exfoliante corporal natural',
                   'Lápiz labial hidratante',
                   'Esmalte de uñas en gel',
                   'Toallitas desmaquillantes',
                   'Aceite esencial relajante',
                   'Protector solar facial SPF 50',
                   'Serum rejuvenecedor',
                   'Crema antiarrugas de noche',
                   'Cera depilatoria para piel sensible',
                   'Desodorante natural sin aluminio',
                   'Cepillo facial eléctrico',
                   'Corrector de ojeras de larga duración',
                   'Tónico facial revitalizante',
                   'Acondicionador sin sulfatos',
                   'Mascarilla facial de arcilla',
                   'Rímel de volumen intenso',
                   'Paleta de sombras neutras',
                   'Cortador de uñas profesional',
                   'Kit de cuidado de cejas',
                   'Crema para manos hidratante',
                   'Jabón exfoliante artesanal',
                   'Tratamiento para puntas abiertas',
                   'Tijeras para corte de cabello',
                ],
                'descriptions' => [
                    'Crema para hidratar y proteger la piel del rostro.',
                    'Set de brochas para aplicar maquillaje de manera precisa.',
                    'Perfume con fragancia floral ideal para el día.',
                    'Champú especializado en fortalecer el cabello.',
                    'Gel que elimina impurezas y controla el exceso de grasa.',
                    'Mascarilla capilar que repara el cabello dañado.',
                    'Base de maquillaje con acabado mate y cobertura total.',
                    'Exfoliante para eliminar células muertas de la piel.',
                    'Lápiz labial que hidrata y da color duradero.',
                    'Esmalte en gel para un acabado brillante y resistente.',
                    'Toallitas suaves para remover maquillaje fácilmente.',
                    'Aceite esencial que ayuda a reducir el estrés.',
                    'Protector solar de alta protección contra rayos UV.',
                    'Serum que reduce líneas de expresión y manchas.',
                    'Crema que nutre y regenera la piel mientras duermes.',
                    'Cera depilatoria con fórmula suave para la piel.',
                    'Desodorante con ingredientes naturales y sin químicos.',
                    'Cepillo eléctrico para una limpieza profunda del rostro.',
                    'Corrector de ojeras con alta cobertura.',
                    'Tónico que revitaliza y refresca la piel.',
                    'Acondicionador que hidrata y desenreda el cabello.',
                    'Mascarilla de arcilla que purifica la piel.',
                    'Rímel que da volumen y alarga las pestañas.',
                    'Paleta de sombras en tonos naturales y versátiles.',
                    'Cortador de uñas con diseño ergonómico.',
                    'Kit completo para definir y arreglar las cejas.',
                    'Crema hidratante para mantener manos suaves.',
                    'Jabón natural que limpia y exfolia la piel.',
                    'Tratamiento que sella y repara las puntas abiertas.',
                    'Tijeras diseñadas para cortes de precisión.',
                ],
            ],
            10 => [ // Cámaras y Accesorios
                'titles' => [
                    'Cámara réflex digital',
                    'Lente gran angular 18-55mm',
                    'Trípode de aluminio profesional',
                    'Estuche rígido para cámara',
                    'Kit de limpieza para lentes',
                    'Micrófono externo para cámaras',
                    'Filtro UV para lentes',
                    'Batería recargable para cámaras',
                    'Flash portátil de alta potencia',
                    'Soporte para cámara de acción',
                    'Control remoto inalámbrico',
                    'Estabilizador de cámara gimbal',
                    'Funda protectora para lente',
                    'Tarjeta de memoria 128GB',
                    'Mochila impermeable para equipo fotográfico',
                    'Lente teleobjetivo 70-200mm',
                    'Parasol para lente DSLR',
                    'Cargador rápido para baterías de cámara',
                    'Adaptador de montura para lentes',
                    'Foco LED para fotografía',
                    'Reflector plegable 5 en 1',
                    'Cinta adhesiva para cables',
                    'Difusor para flash',
                    'Filtro ND ajustable',
                    'Lente macro para primeros planos',
                    'Cable HDMI para cámaras',
                    'Adaptador para trípode',
                    'Grip de batería para cámara DSLR',
                    'Monitor externo para cámaras',
                    'Cargador solar para cámaras',
                ],
                'descriptions' => [
                    'Cámara réflex digital con funciones avanzadas.',
                    'Lente versátil ideal para paisajes y retratos.',
                    'Trípode robusto y ligero para estabilidad.',
                    'Estuche rígido que protege el equipo fotográfico.',
                    'Kit completo para mantener los lentes limpios.',
                    'Micrófono de calidad para grabaciones claras.',
                    'Filtro UV que protege y mejora la calidad de las fotos.',
                    'Batería recargable compatible con múltiples modelos.',
                    'Flash compacto con alta capacidad lumínica.',
                    'Soporte ajustable para cámaras deportivas.',
                    'Control remoto para manejar la cámara a distancia.',
                    'Estabilizador para videos fluidos y profesionales.',
                    'Funda para proteger los lentes de rayaduras.',
                    'Tarjeta de memoria de alta velocidad.',
                    'Mochila diseñada para transportar equipo de forma segura.',
                    'Lente teleobjetivo ideal para capturar detalles lejanos.',
                    'Parasol para reducir reflejos y proteger el lente.',
                    'Cargador rápido compatible con baterías estándar.',
                    'Adaptador que permite usar diferentes monturas.',
                    'Foco LED con intensidad ajustable.',
                    'Reflector para mejorar la iluminación en fotografías.',
                    'Cinta para sujetar y organizar cables.',
                    'Difusor para suavizar la luz del flash.',
                    'Filtro ND para controlar la exposición en condiciones brillantes.',
                    'Lente macro para capturar detalles diminutos.',
                    'Cable HDMI para transmitir contenido en alta calidad.',
                    'Adaptador que asegura la cámara al trípode.',
                    'Grip para extender la duración de la batería.',
                    'Monitor externo con alta resolución.',
                    'Cargador solar ideal para exteriores.',
                ],
            ],
            11 => [ // Celulares y Telefonía
                'titles' => [
                    'Samsung Galaxy S23 Ultra', 
                    'iPhone 14 Pro Max', 
                    'Xiaomi Redmi Note 12', 
                    'Google Pixel 7 Pro', 
                    'Motorola Edge 40', 
                    'Huawei P60 Pro',
                    'Nokia G21', 
                    'Sony Xperia 1 V', 
                    'OnePlus Nord CE 3',
                    'Realme GT Neo 5', 
                    'Poco X5 Pro', 
                    'Asus ROG Phone 7',
                    'BlackBerry Key2', 
                    'Honor Magic5 Pro', 
                    'Oppo Find X6 Pro',
                    'ZTE Axon 50', 
                    'Vivo X90 Pro', 
                    'Lenovo Legion Phone Duel',
                    'Samsung Galaxy Z Fold 5', 
                    'iPhone SE 3rd Gen', 
                    'Xiaomi Mi 13 Lite',
                    'Realme Narzo 60', 
                    'Sony Xperia 10 IV', 
                    'LG Velvet 5G',
                    'Google Pixel 6a', 
                    'Motorola Moto G Stylus 5G', 
                    'Huawei Mate 50',
                    'OnePlus 11', 
                    'Asus Zenfone 10', 
                    'Samsung Galaxy A54',
                ],
                'descriptions' => [
                    'Pantalla AMOLED de alta resolución.', 
                    'Cámara con zoom óptico 10x.', 
                    'Batería de larga duración.', 
                    'Sistema operativo Android 14.', 
                    'Resistente al agua y polvo (IP68).', 
                    'Cámara trasera triple con IA.',
                    'Carga rápida de 120W.', 
                    'Pantalla con frecuencia de actualización de 120Hz.', 
                    'Compatible con 5G.', 
                    'Altavoces estéreo de alta fidelidad.', 
                    'Chipset de última generación.', 
                    'Diseño ergonómico y liviano.', 
                    'Incluye lápiz óptico.', 
                    'Memoria expandible hasta 1TB.', 
                    'Pantalla sin bordes.', 
                    'Modo nocturno para fotos.', 
                    'Compatible con carga inalámbrica.', 
                    'Desbloqueo facial avanzado.', 
                    'Conectividad NFC integrada.', 
                    'Puerto USB-C.', 
                    'Pantalla Gorilla Glass resistente.', 
                    'Batería removible.', 
                    'Actualizaciones de software garantizadas.', 
                    'Ideal para gaming.', 
                    'Integración con servicios en la nube.', 
                    'Disponible en varios colores.', 
                    'Fabricado con materiales reciclados.', 
                    'Cámara frontal de alta calidad.', 
                    'Diseño premium.', 
                    'Perfecto para fotografía profesional.',
                ],
            ],
            12 => [ // Computación
                'titles' => [
                    'Laptop Dell XPS 15', 
                    'MacBook Pro M2', 
                    'Asus ZenBook 14', 
                    'HP Pavilion Gaming', 
                    'Lenovo IdeaPad 3', 
                    'Microsoft Surface Laptop 5',
                    'Acer Predator Helios 300', 
                    'Razer Blade 16', 
                    'MSI Stealth 15M',
                    'Alienware m18', 
                    'Samsung Galaxy Book3 Ultra', 
                    'LG Gram 17',
                    'Apple iMac 24"', 
                    'Dell G5 Desktop', 
                    'Asus ROG Strix G16',
                    'HP Spectre x360', 
                    'Lenovo ThinkPad X1 Carbon', 
                    'Microsoft Surface Studio 2+',
                    'Chromebook Pixelbook Go', 
                    'Acer Aspire 7', 
                    'MSI Creator Z17',
                    'Gigabyte Aero 15', 
                    'HP Envy 14', 
                    'Apple Mac Mini M2',
                    'Dell Inspiron 16', 
                    'Asus TUF Gaming F15', 
                    'Samsung Smart Monitor M8',
                    'Raspberry Pi 4', 
                    'Intel NUC 12 Extreme', 
                    'Corsair One i300',
                ],
                'descriptions' => [
                    'Procesador Intel de última generación', 
                    'Pantalla 4K Ultra HD.',
                    'Diseño ultradelgado y ligero', 
                    'Tarjeta gráfica dedicada',
                    'Teclado retroiluminado', 
                    'Batería de hasta 10 horas de duración',
                    'Almacenamiento SSD de alta velocidad', 
                    'Cámara web de alta definición',
                    'Compatible con Wi-Fi 6E', 
                    'Ideal para multitarea', 
                    'Incluye sistema operativo Windows 11', 
                    'Pantalla táctil integrada', 
                    'Altavoces estéreo mejorados', 
                    'Soporte para VR', 
                    'Puertos USB-C y Thunderbolt', 
                    'Construcción en aluminio', 
                    'Refrigeración optimizada para gaming', 
                    'Compatible con monitores externos', 
                    'Tecnología de carga rápida', 
                    'Incluye teclado y mouse', 
                    'Diseño ergonómico para trabajar', 
                    'Pantalla sin reflejos', 
                    'Reparaciones fáciles', 
                    'Actualización de hardware sencilla', 
                    'Perfecto para desarrolladores de software', 
                    'Preinstalación de Office 365', 
                    'Conexión Bluetooth avanzada', 
                    'Almacenamiento expandible', 
                    'Protección contra malware integrada', 
                    'Sistema de audio premium',
                ],
            ],
            13=> [ //Consolas y Video Juegos
                'titles' => [
                    'PlayStation 5',
                    'Xbox Series X',
                    'Nintendo Switch OLED',
                    'Control inalámbrico DualSense',
                    'Volante Logitech G29',
                    'Headset Gamer HyperX',
                    'Tarjeta de expansión SSD para Xbox',
                    'Consola retro Super Nintendo Classic',
                    'Videojuego The Legend of Zelda: Breath of the Wild',
                    'Call of Duty: Modern Warfare II',
                    'Minecraft para PS5',
                    'FIFA 24',
                    'Ratón Gamer Razer Viper',
                    'Teclado mecánico RGB para gamers',
                    'Base de carga para controles PS5',
                    'Cámara HD para PS5',
                    'Adaptador de red para Nintendo Switch',
                    'Audífonos inalámbricos para Xbox',
                    'Kit de accesorios para Nintendo Switch',
                    'Estuche protector para PS5',
                    'Videojuego Mario Kart 8 Deluxe',
                    'Mando Pro para Nintendo Switch',
                    'Joystick para simuladores de vuelo',
                    'Tarjeta de regalo PlayStation Store',
                    'Monitor gamer 144Hz',
                    'Silla gamer ergonómica',
                    'Control Elite Series 2 para Xbox',
                    'Set de luces LED para setup gamer',
                    'Cámara VR para PS5',
                    'Steam Deck 512GB',
                ],
                'descriptions' => [
                    'Consola de última generación con gráficos impresionantes.',
                    'Sistema de juego de alta potencia para gamers avanzados.',
                    'Versión mejorada de la Nintendo Switch con pantalla OLED.',
                    'Control ergonómico para una experiencia de juego inmersiva.',
                    'Perfecto para simuladores de carreras con máxima precisión.',
                    'Audífonos con sonido envolvente para una experiencia inmersiva.',
                    'Ampliación de almacenamiento para juegos de Xbox.',
                    'Consola retro para disfrutar juegos clásicos.',
                    'Aclamado juego de aventura y exploración.',
                    'Shooter en primera persona con acción sin igual.',
                    'Juego de construcción y creatividad para todas las edades.',
                    'Simulación de fútbol con gráficos realistas.',
                    'Ratón de alta velocidad para juegos competitivos.',
                    'Teclado con iluminación RGB para personalizar tu experiencia.',
                    'Base para cargar dos controles al mismo tiempo.',
                    'Cámara para transmitir y grabar en alta definición.',
                    'Adaptador para mejorar la conectividad de la consola.',
                    'Audífonos diseñados especialmente para consolas Xbox.',
                    'Todo lo que necesitas para mejorar tu experiencia de juego.',
                    'Protección contra polvo y rayones para tu consola.',
                    'Juego de carreras lleno de diversión para toda la familia.',
                    'Control profesional para jugadores exigentes.',
                    'Joystick para juegos de simulación de vuelo.',
                    'Tarjeta para comprar juegos y contenido adicional.',
                    'Pantalla con alta frecuencia de actualización para gaming.',
                    'Silla diseñada para largas sesiones de juego.',
                    'Control premium con opciones de personalización avanzadas.',
                    'Luces LED para personalizar tu espacio gamer.',
                    'Cámara diseñada para experiencias de realidad virtual.',
                    'Dispositivo portátil para juegos de PC en movimiento.',
                ],
            ],
            14 => [ //Construccion
                'titles' => [
                    'Taladro inalámbrico',
                    'Caja de herramientas multiusos',
                    'Martillo profesional',
                    'Cinta métrica de 5 metros',
                    'Juego de destornilladores',
                    'Nivel láser de alta precisión',
                    'Sierra eléctrica portátil',
                    'Amoladora angular',
                    'Generador eléctrico portátil',
                    'Compresor de aire industrial',
                    'Cortadora de cerámica',
                    'Soldadora eléctrica',
                    'Brocas para concreto',
                    'Escalera plegable de aluminio',
                    'Cinturón portaherramientas',
                    'Guantes de trabajo reforzados',
                    'Lentes de seguridad antiempañantes',
                    'Mascarilla respiradora profesional',
                    'Pistola de calor industrial',
                    'Tijeras para cortar metal',
                    'Motosierra de gasolina',
                    'Esmeriladora de banco',
                    'Juego de llaves inglesas',
                    'Cemento adhesivo resistente',
                    'Pintura impermeable para exteriores',
                    'Andamio móvil',
                    'Carretilla de acero reforzado',
                    'Detector de metales para construcción',
                    'Plomada de precisión',
                    'Kit de reparación de paredes',
                ],
                'descriptions' => [
                    'Herramienta indispensable para perforaciones rápidas y precisas.',
                    'Incluye herramientas básicas para reparaciones y construcción.',
                    'Resistente y duradero para trabajos intensos.',
                    'Medición precisa para proyectos de construcción.',
                    'Set de destornilladores para múltiples aplicaciones.',
                    'Asegura la precisión en alineaciones y mediciones.',
                    'Ideal para cortes rápidos y efectivos.',
                    'Para desbastar y pulir con potencia y precisión.',
                    'Proporciona energía en sitios de construcción remotos.',
                    'Equipo industrial para herramientas neumáticas.',
                    'Corta azulejos y cerámica con facilidad.',
                    'Para trabajos de soldadura de alta resistencia.',
                    'Conjunto de brocas diseñadas para perforar concreto.',
                    'Ligera y resistente, ideal para trabajos en altura.',
                    'Permite llevar herramientas de manera cómoda y organizada.',
                    'Protección óptima para manos en tareas exigentes.',
                    'Protección ocular contra partículas y polvo.',
                    'Filtra partículas y gases tóxicos durante el trabajo.',
                    'Útil para remover pintura o doblar materiales.',
                    'Corte preciso de láminas de metal.',
                    'Poderosa herramienta para cortar madera y ramas.',
                    'Para lijar y pulir materiales con estabilidad.',
                    'Llaves de diferentes tamaños para ajustes mecánicos.',
                    'Adhesivo de alta calidad para construcción.',
                    'Protección contra humedad y lluvia en paredes exteriores.',
                    'Estructura móvil para trabajos en altura.',
                    'Transporte de materiales pesados con facilidad.',
                    'Detecta cables y tubos en paredes y pisos.',
                    'Para garantizar mediciones verticales exactas.',
                    'Incluye materiales para reparar daños en paredes.',
                ],
            ],
            15 => [ //Deportes Y Fitness
                'titles' => [
                    'Pelota de fútbol',
                    'Bicicleta de montaña',
                    'Cuerda para saltar',
                    'Guantes de boxeo',
                    'Pesas ajustables',
                    'Colchoneta de yoga',
                    'Reloj deportivo',
                    'Patineta',
                    'Bolsa para gimnasio',
                    'Raqueta de tenis',
                    'Set de mancuernas',
                    'Banda elástica',
                    'Balón de baloncesto',
                    'Kit de entrenamiento en casa',
                    'Camiseta deportiva',
                    'Zapatos para correr',
                    'Botella de agua deportiva',
                    'Casco para bicicleta',
                    'Rodilleras deportivas',
                    'Pesa rusa',
                    'Trampolín',
                    'Saco de boxeo',
                    'Tienda de campaña',
                    'Lentes para natación',
                    'Aro de pilates',
                    'Banco de pesas',
                    'Kit de buceo',
                    'Bicicleta estática',
                    'Rueda para abdominales',
                    'Cinturón de levantamiento de pesas',
                ],
                'descriptions' => [
                    'Pelota ideal para partidos de fútbol.',
                    'Bicicleta con suspensión para terrenos difíciles.',
                    'Cuerda ligera y resistente para entrenamiento.',
                    'Guantes acolchados para mayor protección.',
                    'Pesas con ajuste rápido de peso.',
                    'Colchoneta antideslizante para ejercicios.',
                    'Reloj con funciones de seguimiento de actividad.',
                    'Patineta resistente y de diseño moderno.',
                    'Bolsa espaciosa para llevar tu equipo.',
                    'Raqueta ligera con excelente manejo.',
                    'Conjunto de mancuernas con diferentes pesos.',
                    'Banda ideal para ejercicios de resistencia.',
                    'Balón con diseño profesional.',
                    'Kit completo para entrenar en casa.',
                    'Camiseta con tejido transpirable.',
                    'Zapatos diseñados para máxima comodidad al correr.',
                    'Botella con aislamiento para bebidas frías.',
                    'Casco con protección certificada.',
                    'Rodilleras ajustables y acolchadas.',
                    'Pesa rusa ideal para entrenamientos funcionales.',
                    'Trampolín compacto para uso en casa.',
                    'Saco resistente para boxeo y kickboxing.',
                    'Tienda ligera y fácil de montar.',
                    'Lentes con ajuste ergonómico.',
                    'Aro resistente para ejercicios de pilates.',
                    'Banco ajustable para entrenamiento con pesas.',
                    'Equipo de buceo para principiantes.',
                    'Bicicleta con programas de entrenamiento.',
                    'Rueda con agarre cómodo para abdominales.',
                    'Cinturón reforzado para levantamiento de pesas.',
                ],
            ],
            16 => [ //Electrodomesticos
                'titles' => [
                    'Refrigerador de dos puertas',
                    'Horno microondas',
                    'Licuadora de alta potencia',
                    'Aspiradora inalámbrica',
                    'Cafetera de cápsulas',
                    'Freidora de aire',
                    'Plancha de vapor',
                    'Purificador de aire',
                    'Ventilador de torre',
                    'Lavadora automática',
                    'Secadora de ropa',
                    'Horno eléctrico',
                    'Tostadora de pan',
                    'Exprimidor de cítricos',
                    'Termo eléctrico',
                    'Humidificador ultrasónico',
                    'Cocina de inducción',
                    'Calentador de agua',
                    'Batidora de mano',
                    'Robot aspirador',
                    'Picadora de carne',
                    'Abrelatas eléctrico',
                    'Maquina de helados',
                    'Refrigerador compacto',
                    'Máquina para hacer palomitas',
                    'Deshidratador de alimentos',
                    'Cepillo alisador',
                    'Planchadora a vapor',
                    'Lámpara antimosquitos',
                    'Licuadora portátil',
                ],
                'descriptions' => [
                    'Refrigerador con gran capacidad.',
                    'Horno con funciones avanzadas.',
                    'Licuadora ideal para smoothies.',
                    'Aspiradora ligera y potente.',
                    'Cafetera con diseño moderno.',
                    'Freidora para cocinar sin aceite.',
                    'Plancha eficiente y compacta.',
                    'Purificador para mejorar la calidad del aire.',
                    'Ventilador con control remoto.',
                    'Lavadora con programas automáticos.',
                    'Secadora con sensor de humedad.',
                    'Horno compacto para cocina rápida.',
                    'Tostadora de diseño clásico.',
                    'Exprimidor fácil de usar.',
                    'Termo de rápida recuperación.',
                    'Humidificador silencioso.',
                    'Cocina eficiente en consumo de energía.',
                    'Calentador compacto para el hogar.',
                    'Batidora ligera y ergonómica.',
                    'Robot para limpieza automática.',
                    'Picadora con múltiples accesorios.',
                    'Abrelatas práctico y seguro.',
                    'Máquina ideal para helados caseros.',
                    'Refrigerador para espacios pequeños.',
                    'Palomitas frescas en minutos.',
                    'Deshidratador con capacidad ajustable.',
                    'Cepillo para un alisado perfecto.',
                    'Planchadora ideal para ropa delicada.',
                    'Lámpara eficiente contra insectos.',
                    'Licuadora para llevar a cualquier lugar.',
                ],
            ],
            21 => [ // Inmuebles
                'titles' => [
                    'Casa en el centro',
                    'Departamento con vista al mar',
                    'Terreno amplio',
                    'Oficina equipada',
                    'Local comercial',
                    'Casa de campo',
                    'Penthouse moderno',
                    'Departamento amueblado',
                    'Terreno en zona residencial',
                    'Cabaña en la montaña',
                    'Nave industrial',
                    'Bodega en renta',
                    'Casa con jardín',
                    'Terreno rústico',
                    'Oficina en zona céntrica',
                    'Departamento minimalista',
                    'Casa colonial',
                    'Terreno cerca de la playa',
                    'Edificio de oficinas',
                    'Casa en fraccionamiento privado',
                    'Departamento tipo estudio',
                    'Local en plaza comercial',
                    'Casa con alberca',
                    'Terreno en esquina',
                    'Villa de lujo',
                    'Oficina con estacionamiento',
                    'Casa prefabricada',
                    'Departamento dúplex',
                    'Casa para remodelar',
                    'Terreno comercial',
                ],
                'descriptions' => [
                    'Ubicada en una zona céntrica y accesible',
                    'Hermosa vista al océano',
                    'Ideal para construcción',
                    'Lista para trabajar',
                    'Perfecta para negocios',
                    'Ambiente tranquilo y natural',
                    'Diseño moderno y exclusivo',
                    'Incluye mobiliario completo',
                    'Zona segura y residencial',
                    'Rústica y acogedora',
                    'Espacio industrial amplio',
                    'Perfecta para almacenamiento',
                    'Ideal para familias',
                    'Con excelente ubicación',
                    'En el corazón de la ciudad',
                    'Estilo moderno y funcional',
                    'Estilo clásico y elegante',
                    'Cerca de atractivos turísticos',
                    'Espacios amplios y funcionales',
                    'Seguridad y privacidad garantizadas',
                    'Compacto y funcional',
                    'Alta visibilidad para tu negocio',
                    'Perfecta para relajarse',
                    'Con ubicación estratégica',
                    'Lujosa y sofisticada',
                    'Incluye espacios asignados',
                    'Rápida instalación',
                    'Distribución en dos niveles',
                    'Con grandes posibilidades',
                    'Zona de alto tráfico comercial',
                ],
            ],
            22 => [ // Instrumentos Musicales
                'titles' => [
                    'Guitarra acústica',
                    'Teclado electrónico',
                    'Batería completa',
                    'Violín profesional',
                    'Bajo eléctrico',
                    'Trompeta de concierto',
                    'Flauta transversal',
                    'Guitarra eléctrica',
                    'Piano de cola',
                    'Saxofón alto',
                    'Ukelele de madera',
                    'Cajón peruano',
                    'Timbales latinos',
                    'Arpa clásica',
                    'Micrófono de estudio',
                    'Percusión africana',
                    'Sintetizador digital',
                    'Trompa francesa',
                    'Clarinete de madera',
                    'Set de platillos para batería',
                    'Mandolina tradicional',
                    'Guitarra clásica',
                    'Violonchelo avanzado',
                    'Órgano electrónico',
                    'Fagot para estudiantes',
                    'Banjo de cinco cuerdas',
                    'Acordeón cromático',
                    'Tuba profesional',
                    'Melódica portátil',
                    'Marimba de concierto',
                ],
                'descriptions' => [
                    'Sonido cálido y resonante',
                    'Con múltiples funciones y ritmos',
                    'Perfecta para principiantes y expertos',
                    'Sonido puro y excelente calidad',
                    'Gran definición de tonos graves',
                    'Ideal para presentaciones en vivo',
                    'Diseño ligero y versátil',
                    'Perfecta para géneros variados',
                    'Elegante y potente en sonido',
                    'Para estilos de música moderna',
                    'Compacto y fácil de transportar',
                    'Ideal para ritmos tradicionales',
                    'Instrumento de percusión versátil',
                    'Sonido angelical y clásico',
                    'Captura de audio profesional',
                    'Dale un toque étnico a tu música',
                    'Crea sonidos innovadores',
                    'Perfecta para música clásica',
                    'De gran precisión tonal',
                    'Perfecto complemento para baterías',
                    'Instrumento con un toque folclórico',
                    'Ideal para principiantes',
                    'Sonido profundo y envolvente',
                    'Compacto y versátil',
                    'Para estudiantes y músicos avanzados',
                    'Perfecto para música country',
                    'Instrumento con carácter',
                    'Imponente y resonante',
                    'Fácil de llevar a todas partes', 'Sonido cálido y vibrante',
                ],
            ],
            23 => [ // Joyas y Relojes
                'titles' => [
                    'Anillo de oro blanco',
                    'Reloj automático',
                    'Collar de perlas',
                    'Pulsera de plata',
                    'Aretes de diamante',
                    'Reloj deportivo',
                    'Anillo de compromiso',
                    'Collar con dije de corazón',
                    'Pulsera de oro',
                    'Reloj vintage',
                    'Gargantilla de piedras preciosas',
                    'Broche de cristal',
                    'Manilla de cuero',
                    'Reloj de acero inoxidable',
                    'Anillo de zafiro',
                    'Pendientes de oro',
                    'Collar minimalista',
                    'Reloj inteligente',
                    'Anillo de platino',
                    'Charm de colección',
                    'Pulsera con incrustaciones',
                    'Reloj de cuarzo',
                    'Cadena de oro',
                    'Set de joyas elegantes',
                    'Reloj de edición limitada',
                    'Anillo con grabado personalizado',
                    'Pendientes largos',
                    'Collar vintage',
                    'Pulsera con dijes',
                    'Reloj de buceo',
                ],
                'descriptions' => [
                    'Elegancia y sofisticación',
                    'Movimiento automático preciso',
                    'Clásico y atemporal',
                    'Diseño sencillo y moderno',
                    'Brillo excepcional',
                    'Perfecto para actividades deportivas',
                    'Ideal para momentos especiales',
                    'Un regalo perfecto',
                    'Luce sofisticación',
                    'Estilo retro y único',
                    'Destaca con estilo',
                    'Toque brillante a cualquier outfit',
                    'Duradera y versátil',
                    'Combina con cualquier look',
                    'Color profundo y elegante',
                    'Acentúa cualquier atuendo',
                    'Sencillo pero encantador',
                    'Tecnología y diseño en uno',
                    'Resistente y refinado',
                    'Agrega personalidad a tu estilo',
                    'Diseño con detalles únicos',
                    'Fiable y accesible',
                    'Un clásico de lujo',
                    'Estilo y brillo en conjunto',
                    'Exclusivo y de colección',
                    'Personalización que impacta',
                    'Perfectos para ocasiones formales',
                    'Estilo con un toque nostálgico',
                    'Personalizable para cualquier evento',
                    'Resistente al agua y funcional',
                ],
            ],
            24 => [ // Juegos y Juguetes
                'titles' => [
                    'Rompecabezas de 1000 piezas',
                    'Muñeca interactiva',
                    'Carrito a control remoto',
                    'Lego de construcción',
                    'Pelota de fútbol',
                    'Drone con cámara',
                    'Tren eléctrico',
                    'Kit de ciencia',
                    'Tablero de ajedrez',
                    'Set de plastilina',
                    'Peluches gigantes',
                    'Pistola de agua',
                    'Bicicleta infantil',
                    'Patineta clásica',
                    'Set de magia',
                    'Juego de mesa Clue',
                    'Robot programable',
                    'Camión de bomberos',
                    'Juego de tiro al blanco',
                    'Casa de muñecas',
                    'Puzzle 3D',
                    'Patines ajustables',
                    'Coche de carreras',
                    'Juego de bolos',
                    'Trompo metálico',
                    'Bloques educativos',
                    'Microscopio para niños',
                    'Juegos didácticos',
                    'Nerf de largo alcance',
                    'Guitarra de juguete',
                ],
                'descriptions' => [
                    'Ideal para pasar horas de diversión',
                    'Responde y habla con los niños',
                    'Velocidad y emoción garantizadas',
                    'Despierta la imaginación',
                    'Para juegos al aire libre',
                    'Captura vistas aéreas increíbles',
                    'Diversión para todas las edades',
                    'Aprendizaje y entretenimiento',
                    'Desafía tu mente',
                    'Fomenta la creatividad',
                    'Suaves y adorables',
                    'Perfecta para días calurosos',
                    'Fomenta el deporte',
                    'Diseño clásico y resistente',
                    'Sorprende a todos con trucos',
                    'Diversión en grupo',
                    'Desarrolla habilidades tecnológicas',
                    'Perfecto para juegos de rol',
                    'Mejora la puntería',
                    'Detalles encantadores',
                    'Desafío para expertos',
                    'Diversión en movimiento',
                    'Velocidad en miniatura',
                    'Fomenta la precisión',
                    'Juguete tradicional',
                    'Aprende jugando',
                    'Inspira a futuros científicos',
                    'Herramientas para aprender y explorar',
                    'Diversión y acción garantizada',
                    'Inicia en el mundo de la música',
                ],
            ],
            25 => [ // Libros, Revistas y Comics
                'titles' => [
                    'El Juego De Ender',
                    'Cien Años De Soledad',
                    'Harry Potter y la Piedra Filosofal',
                    'El Señor De Los Anillos',
                    '1984',
                    'La Casa De Los Espíritus',
                    'El Alquimista',
                    'Orgullo y Prejuicio',
                    'Don Quijote De La Mancha',
                    'Los Pilares De La Tierra',
                    'Crónica De Una Muerte Anunciada',
                    'El Código Da Vinci',
                    'Los Miserables',
                    'Matar A Un Ruiseñor',
                    'La Sombra Del Viento',
                    'La Trilogía De La Fundación',
                    'Cumbres Borrascosas',
                    'Fahrenheit 451',
                    'El Retrato De Dorian Gray',
                    'Drácula',
                    'El Nombre Del Viento',
                    'El Hobbit',
                    'Rayuela',
                    'La Guerra De Los Mundos',
                    'La Metamorfosis',
                    'El Gran Gatsby',
                    'El Corazón Delator',
                    'El Psicoanalista',
                    'La Chica Del Tren',
                    'Comic El Regreso Del Caballero Oscuro, Edición Especial',
                ],
                'descriptions' => [
                    'Una obra maestra de la ciencia ficción sobre un niño prodigio que salva a la humanidad.',
                    'La historia épica de la familia Buendía, en el mágico Macondo, escrita por Gabriel García Márquez.',
                    'La primera entrega de la saga mágica que sigue a un joven mago en su lucha contra el mal.',
                    'La épica fantasía que narra la lucha contra el oscuro señor Sauron.',
                    'Una distopía que explora un futuro totalitario donde la vigilancia es omnipresente.',
                    'La historia de la vida de Clara, una joven que posee poderes psíquicos, y su familia.',
                    'La obra de Paulo Coelho sobre la búsqueda personal de un joven en la vida.',
                    'La historia de amor entre Elizabeth Bennet y el orgulloso Mr. Darcy.',
                    'Las aventuras de un caballero enloquecido por la lectura, en su lucha contra los molinos de viento.',
                    'Una de las novelas históricas más importantes, centrada en la construcción de una catedral.',
                    'Una novela de suspenso sobre el asesinato de un hombre en una ciudad costera.',
                    'Un thriller histórico que entrelaza arte, religión y misterio.',
                    'El clásico de Victor Hugo sobre la lucha de los oprimidos y la redención.',
                    'La historia conmovedora de una niña que crece en un pueblo del sur de los Estados Unidos.',
                    'Una novela que explora los secretos oscuros y misterios en la Barcelona de la posguerra.',
                    'Una serie de ciencia ficción que explora la caída y el ascenso de imperios galácticos.',
                    'El trágico romance de dos almas perdidas en los páramos de la Inglaterra victoriana.',
                    'Una crítica a la censura y la manipulación del conocimiento en una sociedad distópica.',
                    'Una obra maestra que explora la belleza del hedonismo y la corrupción en la sociedad victoriana.',
                    'La historia de la lucha entre el bien y el mal a través del vampiro más famoso.',
                    'El inicio de la famosa saga de fantasía que sigue al joven mago en su viaje.',
                    'Un estudio profundo de la complejidad de la literatura, la vida y la pasión.',
                    'La invasión alienígena que pone en peligro la supervivencia de la humanidad.',
                    'Una obra maestra de Kafka sobre la transformación y la alienación de un hombre.',
                    'La famosa novela que narra la vida decadente y las relaciones en la sociedad de Nueva York.',
                    'Un relato breve sobre la paranoia y el crimen en la mente humana.',
                    'El inquietante thriller psicológico que explora el misterio detrás de una desaparición.',
                    'Un thriller que explora la mente de un psicoanalista ante una amenaza mortal.',
                    'Un misterio psicológico que desafía la percepción de la verdad y la mentira.',
                    'Versión de lujo del clásico cómic, imprescindible para los fanáticos del género.',
                ],
            ],
            26 => [ // Música, Películas y Series
                'titles' => [
                    'Abbey Road',
                    'Thriller',
                    'The Dark Side of the Moon',
                    'Back in Black',
                    'Rumours',
                    'A Night at the Opera',
                    'The Wall',
                    'The Rise and Fall of Ziggy Stardust',
                    'Highway to Hell',
                    'Let It Be',
                    'The Velvet Underground & Nico',
                    'Sticky Fingers',
                    'The Joshua Tree',
                    'Born to Run',
                    'London Calling',
                    'Exile on Main St.',
                    'Goodfellas',
                    'Pulp Fiction',
                    'The Shawshank Redemption',
                    'Forrest Gump',
                    'Inception',
                    'The Godfather',
                    'The Dark Knight',
                    'Star Wars: A New Hope',
                    'The Matrix',
                    'Fight Club',
                    'Titanic',
                    'The Lord of the Rings: The Fellowship of the Ring',
                    'Breaking Bad',
                    'Stranger Things',
                ],
                'descriptions' => [
                    'El icónico álbum de The Beatles, conocido por sus canciones atemporales y su portada legendaria.',
                    'El álbum más vendido de todos los tiempos de Michael Jackson, con los éxitos “Billie Jean” y “Thriller”.',
                    'Un viaje psicodélico a través de la música de Pink Floyd, considerado uno de los mejores álbumes de todos los tiempos.',
                    'El legendario álbum de AC/DC, repleto de himnos de rock como “You Shook Me All Night Long”.',
                    'Uno de los álbumes más influyentes de Fleetwood Mac, con canciones como “Go Your Own Way”.',
                    'El álbum de Queen que presenta la famosa ópera rock “Bohemian Rhapsody”.',
                    'El majestuoso álbum de Pink Floyd que cuenta la historia de una alienación personal y social.',
                    'La obra maestra de David Bowie, donde presenta su personaje de Ziggy Stardust.',
                    'El emblemático álbum de AC/DC con el título que se convirtió en un himno del rock.',
                    'El último álbum de estudio de The Beatles, que contiene “Let It Be” y “Across the Universe”.',
                    'El álbum debut de The Velvet Underground, que cambió el curso de la música rock.',
                    'El aclamado álbum de The Rolling Stones con canciones como “Brown Sugar” y “Wild Horses”.',
                    'El exitoso álbum de U2, con “With or Without You” y “I Still Haven’t Found What I’m Looking For”.',
                    'El revolucionario álbum de Bruce Springsteen, que inspiró a generaciones con su himno “Born to Run”.',
                    'El álbum doble de The Clash que define el punk rock de los años 70 y 80.',
                    'El legendario álbum de The Rolling Stones grabado en el sur de Estados Unidos, lleno de alma y rock.',
                    'La película épica sobre la mafia que fue dirigida por Martin Scorsese y protagonizada por Robert De Niro.',
                    'La película de Quentin Tarantino que cambió el cine contemporáneo con sus diálogos icónicos y narrativa no lineal.',
                    'La conmovedora historia sobre la amistad en prisión y la búsqueda de la redención.',
                    'La entrañable película que mezcla comedia y drama mientras narra la vida de Forrest Gump.',
                    'El thriller de Christopher Nolan que desafía la percepción del tiempo y la realidad.',
                    'La obra maestra de Francis Ford Coppola sobre la mafia y el poder familiar.',
                    'La aclamada película de Christopher Nolan que sigue las aventuras del Caballero Oscuro en Gotham.',
                    'El primer capítulo de la famosa saga galáctica que cambió la historia del cine.',
                    'La película de ciencia ficción que revolucionó el cine con su exploración de la realidad y la simulación.',
                    'La película de David Fincher que explora los límites de la psique humana y el consumismo.',
                    'La conmovedora historia de amor que marcó a toda una generación, protagonizada por Leonardo DiCaprio y Kate Winslet.',
                    'La épica adaptación cinematográfica de la obra de Tolkien, que inicia la trilogía de “El Señor de los Anillos”.',
                    'La aclamada serie que sigue a un profesor de química convertido en fabricante de metanfetaminas.',
                    'La serie de terror y ciencia ficción que se ha convertido en un fenómeno cultural.',
                ],
            ],
            27 => [ // Recuerdos, Cotillón y Fiestas
                'titles' => [
                    'Sombrero Fiesta Animado',
                    'Globos Metalizados 10 Piezas',
                    'Piñata Cumpleaños Infantil',
                    'Kit Fiesta Temática Marvel',
                    'Lentejuelas Brillantes para Fiesta',
                    'Cinta Decorativa de Regalo',
                    'Vela Cumpleaños con Número',
                    'Letras Gigantes para Fiesta',
                    'Conos de Confeti para Boda',
                    'Disfraces Infantiles De Halloween',
                    'Bolsas para Regalos con Diseño',
                    'Tazas Personalizadas para Fiestas',
                    'Decoración para Fiesta de Año Nuevo',
                    'Guirnaldas de Papel para Fiesta',
                    'Mantel de Plástico para Fiesta Infantil',
                    'Máscara de Carnaval para Adultos',
                    'Pulseras de Fiesta de Colores',
                    'Banderines de Fiesta',
                    'Estrellas Colgantes para Decoración',
                    'Sombrero de Conejo para Fiesta',
                    'Lámparas LED para Fiestas',
                    'Caramelos Temáticos para Fiestas',
                    'Toppers de Pastel para Cumpleaños',
                    'Collares de Flores para Fiesta',
                    'Tarjetas de Invitación Personalizadas',
                    'Túmulo de Globo para Fiestas',
                    'Bolsa de Sorpresas para Fiesta Infantil',
                    'Cadenas de Papel para Fiesta de Navidad',
                    'Pañuelos para Fiestas Temáticas',
                    'Juguetes de Fiesta para Niños',
                ],
                'descriptions' => [
                    'Sombrero colorido y animado perfecto para cualquier fiesta temática.',
                    'Pack de globos metalizados en diversos colores, ideales para decorar cualquier celebración.',
                    'Piñata de temática infantil para fiesta de cumpleaños, fácil de llenar y romper.',
                    'Kit completo de fiesta con productos de temática Marvel para los fans de los superhéroes.',
                    'Lentejuelas brillantes para añadir un toque de glamour a tu fiesta de noche.',
                    'Cinta decorativa para envolver regalos o para usar en decoración de eventos especiales.',
                    'Vela para pastel con el número de tu preferencia para celebrar tu cumpleaños.',
                    'Letras gigantes de cartón para decorar y personalizar tu fiesta o evento.',
                    'Conos de confeti para bodas, perfectos para lanzar al final de la ceremonia.',
                    'Disfraz infantil para Halloween, con diferentes personajes disponibles para escoger.',
                    'Bolsas de regalo de alta calidad con diseños modernos y divertidos.',
                    'Tazas personalizadas para obsequiar como recuerdo en eventos especiales.',
                    'Decoración festiva para Año Nuevo, incluye guirnaldas y banderines brillantes.',
                    'Guirnalda de papel de colores vivos para decorar salas de fiestas o jardines.',
                    'Mantel de plástico desechable para fiestas infantiles, con temática de superhéroes.',
                    'Máscara de carnaval para adultos, disponible en diferentes estilos y colores.',
                    'Pulseras de fiesta en diversos colores y formas, perfectas para eventos y festivales.',
                    'Banderines con letras personalizadas, ideales para fiestas de cumpleaños o bodas.',
                    'Estrellas decorativas de papel para colgar en el techo y crear un ambiente festivo.',
                    'Sombrero de conejo de peluche para fiestas de primavera o eventos temáticos.',
                    'Lámpara LED de colores, perfecta para iluminar fiestas al aire libre o en interiores.',
                    'Caramelos temáticos para fiestas, personalizables con los colores del evento.',
                    'Toppers decorativos para pasteles de cumpleaños, con diferentes temáticas disponibles.',
                    'Collares de flores para decorar a los invitados durante una fiesta tropical o hawaiana.',
                    'Tarjetas de invitación personalizadas con tema de boda o cumpleaños para invitados.',
                    'Túmulo de globos para decoración de fiestas infantiles, fácil de montar y colorido.',
                    'Bolsa de sorpresas con pequeños obsequios para niños en fiestas temáticas.',
                    'Cadenas de papel decorativas para fiestas de Navidad, con diseño clásico y colorido.',
                    'Pañuelos de colores para fiesta de baile, disponibles en varias tonalidades.',
                    'Juguetes pequeños para niños, perfectos como recuerdos para fiestas infantiles.',
                ],
            ],
            28 => [ // Ropa, Bolsas y Calzado
                'titles' => [
                    'Zapatos de Cuero Para Hombre',
                    'Bolso de Mano de Piel',
                    'Chaqueta de Cuero para Mujer',
                    'Pantalones Deportivos Unisex',
                    'Camiseta de Algodón con Estampado',
                    'Gorra de Béisbol con Logo',
                    'Botines de Mujer en Ante',
                    'Sandalias de Playa para Hombre',
                    'Chaleco de Lana para Invierno',
                    'Pantalón de Trabajo para Hombre',
                    'Mochila de Tela Resistente',
                    'Zapatillas Deportivas para Mujer',
                    'Vestido Corto de Verano',
                    'Pantalones Vaqueros de Corte Slim',
                    'Bolso de Mano con Correa Ajustable',
                    'Botas de Invierno de Mujer',
                    'Cinturón de Cuero para Hombre',
                    'Sudadera con Capucha para Niño',
                    'Botas de Lluvia para Mujer',
                    'Pantalones Cortos de Tela Ligera',
                    'Camiseta Sin Mangas para Hombre',
                    'Zapatillas de Running para Hombre',
                    'Bolso de Viaje de Mano',
                    'Gorro de Invierno con Forro Polar',
                    'Chaqueta de Invierno con Capucha',
                    'Blusa de Seda para Mujer',
                    'Billetera de Cuero para Hombre',
                    'Sandalias de Cuero para Mujer',
                    'Zapatos de Noche para Mujer',
                    'Bolso Tote De Cuero Vegano, Diseño Minimalista',
                ],
                'descriptions' => [
                    'Zapatos de cuero de alta calidad, ideales para ocasiones formales o casuales.',
                    'Bolso de mano de piel genuina, perfecto para el día a día o eventos especiales.',
                    'Chaqueta de cuero para mujer, con diseño elegante y moderno, perfecta para las noches frescas.',
                    'Pantalones deportivos cómodos y versátiles para hombres y mujeres de todas las edades.',
                    'Camiseta de algodón con estampado divertido y colores vibrantes, cómoda y fresca.',
                    'Gorra de béisbol con logo bordado, ideal para deportes o como accesorio casual.',
                    'Botines de mujer en ante suave, adecuados para el clima frío o como complemento de estilo.',
                    'Sandalias cómodas y ligeras, perfectas para días de verano y playa.',
                    'Chaleco de lana para invierno, ligero pero cálido, ideal para layering.',
                    'Pantalón de trabajo resistente para hombres, con bolsillos y estilo práctico.',
                    'Mochila resistente y ligera, ideal para viajes o uso escolar diario.',
                    'Zapatillas deportivas de mujer, diseñadas para confort y rendimiento en actividades físicas.',
                    'Vestido corto de verano, fresco y elegante para ocasiones informales o vacaciones.',
                    'Pantalones vaqueros de corte slim para hombre, modernos y cómodos para el uso diario.',
                    'Bolso de mano con correa ajustable, práctico y espacioso, adecuado para diversas ocasiones.',
                    'Botas de invierno de mujer, forradas para mantener los pies calientes en el clima frío.',
                    'Cinturón de cuero para hombre, elegante y resistente, para todo tipo de ocasiones.',
                    'Sudadera con capucha para niño, suave y cómoda, perfecta para días fríos o relajados.',
                    'Botas de lluvia para mujer, impermeables y cómodas, ideales para días lluviosos.',
                    'Pantalones cortos de tela ligera, cómodos para los días calurosos de verano.',
                    'Camiseta sin mangas para hombre, fresca y cómoda para los días cálidos.',
                    'Zapatillas de running para hombre, diseñadas para máximo confort en carreras largas.',
                    'Bolso de viaje de mano, espacioso y con compartimentos para organizar pertenencias.',
                    'Gorro de invierno con forro polar, ideal para mantener el calor en los días fríos.',
                    'Chaqueta de invierno con capucha, resistente al viento y al frío, esencial para el invierno.',
                    'Blusa de seda para mujer, elegante y suave, ideal para ocasiones formales o de noche.',
                    'Billetera de cuero para hombre, compacta y elegante, con varios compartimentos.',
                    'Sandalias de cuero para mujer, cómodas y de estilo clásico, perfectas para el verano.',
                    'Zapatos de noche de mujer, elegantes y sofisticados para eventos especiales.',
                    'Bolso moderno y funcional, perfecto para el uso diario, hecho con materiales ecológicos.',
                ],
            ],
            29 => [ // Salud y Equipamiento Médico
                'titles' => [
                    'Termómetro digital de alta precisión',
                    'Oxímetro de pulso portátil',
                    'Monitor de presión arterial automático',
                    'Mascarillas quirúrgicas desechables',
                    'Botiquín de primeros auxilios completo',
                    'Silla de ruedas plegable ligera',
                    'Cama hospitalaria ajustable',
                    'Concentrador de oxígeno compacto',
                    'Nebulizador ultrasónico para uso doméstico',
                    'Tensiómetro manual con estetoscopio',
                    'Muletas ajustables de aluminio',
                    'Lámpara de luz ultravioleta desinfectante',
                    'Tira reactiva para glucosa en sangre',
                    'Báscula digital para uso médico',
                    'Monitor de frecuencia cardíaca',
                    'Camisón quirúrgico desechable',
                    'Termómetro infrarrojo sin contacto',
                    'Gafas de protección médica',
                    'Gel antibacterial 1 litro',
                    'Guantes de nitrilo sin polvo',
                    'Cabestrillo para brazo ajustable',
                    'Bastón ortopédico ergonómico',
                    'Mascarillas KN95 certificadas',
                    'Alcohol en gel con dispensador',
                    'Venda elástica de compresión',
                    'Esfigmomanómetro profesional',
                    'Respirador desechable N95',
                    'Saturómetro pediátrico de dedo',
                    'Faja lumbar de soporte médico',
                    'Caja de bisturíes desechables',
                ],
                'descriptions' => ['Termómetro digital con lectura rápida y pantalla LCD.',
                    'Oxímetro portátil para medir niveles de oxígeno y pulso.',
                    'Monitor automático para controlar la presión arterial.',
                    'Mascarillas quirúrgicas desechables de 3 capas, paquete de 50.',
                    'Botiquín completo con accesorios para emergencias médicas.',
                    'Silla de ruedas plegable de aluminio ligera y resistente.',
                    'Cama hospitalaria con ajuste manual y barandales de seguridad.',
                    'Concentrador de oxígeno compacto para uso personal.',
                    'Nebulizador ultrasónico portátil para tratamiento respiratorio.',
                    'Tensiómetro manual con estetoscopio incluido para uso profesional.',
                    'Muletas ajustables con diseño ergonómico y antideslizante.',
                    'Lámpara UV para desinfección de superficies y ambientes.',
                    'Tiras reactivas para monitoreo de glucosa en sangre.',
                    'Báscula digital precisa para uso médico y doméstico.',
                    'Monitor portátil de frecuencia cardíaca con pantalla.',
                    'Camisón quirúrgico desechable con ajuste cómodo.',
                    'Termómetro infrarrojo para medición sin contacto.',
                    'Gafas protectoras con material resistente a impactos.',
                    'Gel antibacterial con propiedades hidratantes y sin enjuague.',
                    'Guantes de nitrilo resistentes y libres de látex.',
                    'Cabestrillo ajustable para soporte de brazo lesionado.',
                    'Bastón ortopédico con mango ergonómico y base antideslizante.',
                    'Mascarillas KN95 de alta eficiencia de filtración.',
                    'Alcohol en gel con dispensador para desinfección rápida.',
                    'Venda elástica de compresión para soporte de lesiones.',
                    'Esfigmomanómetro profesional de alta precisión.',
                    'Respirador N95 para máxima protección respiratoria.',
                    'Saturómetro pediátrico con diseño amigable para niños.',
                    'Faja lumbar para soporte y alivio de dolores de espalda.',
                    'Bisturíes desechables esterilizados, paquete de 10.',
                ],
            ],
            30 => [ // Servicios
                'titles' => [
                    'Servicio de limpieza profunda para hogares',
                    'Reparación de electrodomésticos',
                    'Clases particulares de matemáticas',
                    'Cuidado de mascotas a domicilio',
                    'Mantenimiento de jardines',
                    'Fotografía profesional para eventos',
                    'Diseño gráfico personalizado',
                    'Asesoría legal empresarial',
                    'Clases de cocina internacional',
                    'Reparación de computadoras y laptops',
                    'Pintura de interiores y exteriores',
                    'Servicio de catering para eventos',
                    'Clases de yoga personalizadas',
                    'Traducción de documentos oficiales',
                    'Reparación de teléfonos móviles',
                    'Diseño de páginas web modernas',
                    'Clases de música a domicilio',
                    'Asesoría en marketing digital',
                    'Servicio de niñera confiable',
                    'Instalación de sistemas de seguridad',
                    'Consultoría financiera personal',
                    'Diseño de interiores y decoración',
                    'Clases de idiomas personalizados',
                    'Mantenimiento de autos a domicilio',
                    'Planificación de bodas y eventos',
                    'Reparación de plomería y fugas',
                    'Capacitación empresarial',
                    'Servicio de transporte privado',
                    'Arreglo de ropa y costura',
                    'Creación de contenido audiovisual',
                ],
                'descriptions' => [
                    'Limpieza profesional de pisos, muebles y ventanas.',
                    'Reparación y mantenimiento de electrodomésticos en el hogar.',
                    'Clases individuales para mejorar el aprendizaje de matemáticas.',
                    'Cuidado especializado de mascotas en su hogar.',
                    'Servicios de poda, riego y decoración de jardines.',
                    'Fotografía profesional para bodas y eventos especiales.',
                    'Diseño gráfico creativo para logos, posters y más.',
                    'Asesoría legal para pequeñas y medianas empresas.',
                    'Clases prácticas de cocina con recetas internacionales.',
                    'Reparación técnica de hardware y software de computadoras.',
                    'Pintura profesional para mejorar el aspecto de tu hogar.',
                    'Catering con menú personalizado para eventos sociales.',
                    'Clases privadas de yoga para mejorar tu bienestar.',
                    'Traducción certificada para documentos legales.',
                    'Reparación de pantallas y software de teléfonos móviles.',
                    'Creación de sitios web funcionales y atractivos.',
                    'Clases de guitarra, piano o violín a domicilio.',
                    'Asesoramiento en estrategias de marketing digital.',
                    'Niñeras profesionales con experiencia comprobada.',
                    'Instalación de cámaras y alarmas de seguridad.',
                    'Orientación financiera para alcanzar metas económicas.',
                    'Decoración de interiores con asesoramiento profesional.',
                    'Clases de inglés, francés o alemán personalizadas.',
                    'Mantenimiento y revisión de autos en casa.',
                    'Organización y planificación de bodas y eventos.',
                    'Solución rápida a problemas de plomería en el hogar.',
                    'Cursos y talleres para formación empresarial.',
                    'Servicio de transporte seguro y privado.',
                    'Ajuste y arreglo de prendas de ropa a medida.',
                    'Producción de videos y contenido audiovisual creativo.',
                ],
            ],
        ];

        foreach ($categories as $categoryId => $data) {
            $totalProducts = count($data['titles']); // Total de títulos disponibles en esta categoría
            for ($i = 0; $i < $totalProducts; $i++) { // 30 productos por categoría
                Product::create([
                    'title' => $data['titles'][$i],
                    'description' => $data['descriptions'][$i],
                    'condition' => ['new', 'used', 'reaconditioned'][array_rand(['new', 'used', 'reaconditioned'])],
                    'stock' => rand(10, 200),
                    'price' => rand(100, 5000),
                    'publication_type' => ['free', 'classic', 'premium'][array_rand(['free', 'classic', 'premium'])],
                    'warranty_type' => ['manufacturer', 'seller'][array_rand(['manufacturer', 'seller'])],
                    'warranty_duration' => rand(1, 24),
                    'warranty_duration_type' => ['days', 'months', 'years'][array_rand(['days', 'months', 'years'])],
                    'status' => ['draft', 'published'][array_rand(['draft', 'published'])],
                    'user_id' => rand(1, 9),
                    'category_id' => $categoryId,
                ]);
            }
        }
    }
}
